### ISSUE TITLE
使用poco的click方法提示点击到屏幕外

### ISSUE THREAD

**Issue by ongmaker** [AirtestProject/Poco#117]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
unity ngui
切换panel后,使用poco的click方法提示点击到屏幕外报错(ui在屏幕范围内).
此时poco切换到inspactor模式,点击ui树不会出现框
```
（在这里粘贴traceback或其他报错信息）
```======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "E:\AutoTestScripts\main.air\main.py", line 268, in <module>
    Main()
  File "E:\AutoTestScripts\main.air\main.py", line 26, in Main
    MainScene()
  File "E:\AutoTestScripts\main.air\main.py", line 79, in MainScene
    HeroUpgrade()
  File "E:\AutoTestScripts\main.air\main.py", line 218, in HeroUpgrade
    poco("DoNotDestroyed").child("MainScenePanel").child("HeroInfo").child("1").focus([0.5, 2.5]).click()
  File "poco\proxy.py", line 23, in wrapped
  File "poco\proxy.py", line 285, in click
  File "poco\pocofw.py", line 247, in click
poco.exceptions.InvalidOperationException: Click position out of screen. pos=[8.949184771860219, 256.33047439407994]

----------------------------------------------------------------------
Ran 1 test in 11.439s

FAILED (errors=1)
[05:04:33][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -s ZTDU99AATSSO4POF forward --remove tcp:14866
[05:04:33][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -s ZTDU99AATSSO4POF forward --remove tcp:15977
[05:04:33][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -s ZTDU99AATSSO4POF forward --remove tcp:12348
[05:04:33][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
[Finished]


**复现步骤**
在一个场景内有两个uipanel, 面板1使用poco点击按钮切换到面板2.再由面板2切换回面板1,此时,使用poco点击面板1上的按钮,出现问题

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:官网最新版
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**Comment by ongmaker** [comment]
....

**Comment by ongmaker** [comment]
可以确定 ui一定是在屏幕内的.poco里在stop和unity里切换刷新几次,有概率恢复正常

**Comment by adolli** [comment]
请问下你当前场景是否有使用两个或两个以上的摄像机？另外麻烦看下你的面板1上的按钮处于哪个Layer以及你的每个摄像机的cullingMask值。
