### ISSUE TITLE
IDE中poco经常启动失败

### ISSUE THREAD

**Issue by lily6543** [AirtestProject/Poco#122]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by lily6543** [comment]
小米8手机，连接IDE，经常获取poco失败
详细日志如下
[Start running..]
save log in 'C:\Users\sherilyxu\AppData\Local\Temp\AirtestIDE\scripts\147ac29033689aa3dcadb38d93b8cd65'
[05:24:51][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 wait-for-device
[05:24:51][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell getprop ro.build.version.sdk
[05:24:52][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell dumpsys activity top
[05:24:53][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell dumpsys package com.netease.nie.yosemite
[05:24:53][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[05:24:53][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell settings get secure default_input_method
[05:24:54][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell ime list -a
[05:24:55][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell dumpsys package com.netease.open.pocoservice
installed version is 39, installer version is 39. force_reinstall=False
[05:24:56][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 shell dumpsys package com.netease.open.pocoservice.test
installed version is None, installer version is 0. force_reinstall=False
[05:24:56][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ebc74fc7 install D:\airtest\AirtestIDE_2018-11-06_py3_win64\poco\drivers\android\lib\pocoservice-debug-androidTest.apk
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "D:\airtest\cases\qqwallet_cfhuiyuan_wechat.air\qqwallet_cfhuiyuan_wechat.py", line 6, in <module>
    poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
  File "poco\drivers\android\uiautomation.py", line 150, in __init__
  File "poco\drivers\android\uiautomation.py", line 190, in _install_service
  File "poco\drivers\android\utils\installation.py", line 31, in install
  File "airtest\core\android\adb.py", line 560, in install_app
  File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[] stderr[adb: failed to install D:\airtest\AirtestIDE_2018-11-06_py3_win64\poco\drivers\android\lib\pocoservice-debug-androidTest.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install com.netease.open.pocoservice.test without first uninstalling.]
]

----------------------------------------------------------------------
Ran 1 test in 6.496s

FAILED (errors=1)
[Finished]

**Comment by yimelia** [comment]
尝试在手机输入法设置中，将yosemite输入法设置为默认输入法，然后再试试。
或者考虑手工卸载掉手机上的`pocoservice-debug-androidTest.apk`，然后再重新尝试下看看？
