### ISSUE TITLE
点击进入游戏按钮的时候报错，

### ISSUE THREAD

**Issue by gzhtest** [AirtestProject/Poco#124]
问题描述细：
只是单纯点击进入游戏按钮。没有其他操作

报错堆栈
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 62, in runTest
  File "F:\code\airtest\test2.air\test2.py", line 10, in <module>
    poco("imgStart").click()
  File "poco\proxy.py", line 23, in wrapped
  File "poco\proxy.py", line 283, in click
  File "poco\proxy.py", line 563, in get_position
  File "poco\proxy.py", line 39, in wrapped
  File "poco\proxy.py", line 684, in attr
  File "poco\proxy.py", line 819, in _do_query
  File "poco\freezeui\hierarchy.py", line 89, in select
  File "poco\sdk\Selector.py", line 77, in select
  File "poco\sdk\Selector.py", line 70, in getRoot
  File "poco\freezeui\hierarchy.py", line 35, in getRoot
  File "poco\utils\simplerpc\utils.py", line 13, in new_func
  File "poco\utils\simplerpc\simplerpc.py", line 78, in wait
poco.utils.simplerpc.simplerpc.RpcTimeoutError: <poco.utils.simplerpc.simplerpc.Callback object at 0x000000000B296FD0>(rid=2a74730d-c0f1-433a-89a7-ef34c5eefb27)

设备：
mumu模拟器

**Comment by adolli** [comment]
麻烦提供一下游戏引擎信息，以及所使用poco版本

/rotten
