### ISSUE TITLE
截图使用poco\utils\airtest\screen.py的getScreen方法报错

### ISSUE THREAD

**Issue by xt3131** [AirtestProject/Poco#132]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
使用poco\utils\airtest\screen.py的getScreen方法报错。
airtest：1.0.25
pocoui:1.0.72

def getScreen(self, width):
        savepath = snapshot()   ####此处调用airtest api snapshot 未传入filename
        return base64.b64encode(open(savepath, 'rb').read()), 'png'

```
（在这里粘贴traceback或其他报错信息）
./usr/local/lib/python3.7/site-packages/pocounit/case.py:211: UserWarning: Fail to stop result emitter: "SiteSnapshot". You can report this error to the developers or just ignore it. Error message: 
"Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pocounit/case.py", line 207, in run
    emitter.stop()
  File "/usr/local/lib/python3.7/site-packages/pocounit/result/site_snapshot.py", line 32, in stop
    self.snapshot('caseEnd')
  File "/usr/local/lib/python3.7/site-packages/pocounit/result/site_snapshot.py", line 38, in snapshot
    self.snapshot_screen(site_id)
  File "/usr/local/lib/python3.7/site-packages/pocounit/result/site_snapshot.py", line 60, in snapshot_screen
    b64img, fmt = self.poco.snapshot()
  File "/usr/local/lib/python3.7/site-packages/poco/pocofw.py", line 433, in snapshot
    return self.agent.screen.getScreen(width)
  File "/usr/local/lib/python3.7/site-packages/poco/utils/airtest/screen.py", line 21, in getScreen
    return base64.b64encode(open(savepath, 'rb').read()), 'png'
TypeError: expected str, bytes or os.PathLike object, not NoneType
"
  .format(emitter.__class__.__name__, traceback.format_exc()))

**复现步骤**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by saucer-man** [comment]
这个问题解决了吗
