### ISSUE TITLE
第二次start_app()启动Unity3D Editor后，执行poco操作会报错

### ISSUE THREAD

**Issue by magicedy** [AirtestProject/Poco#133]
**描述问题bug**
PC上通过start_app()启动Unity3D Editor打开项目，执行完poco操作后，kill掉app，第二次再执行的时候回报错

```
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\mi\AppData\Local\Temp\AirtestIDE\Scripts\untitled.air\untitled.py", line 23, in <module>
    test()
  File "C:\Users\mi\AppData\Local\Temp\AirtestIDE\Scripts\untitled.air\untitled.py", line 19, in test
    poco('StartGame').click()
  File "D:\smb\Software\AirtestIDE_2019-01-15_py3_win64\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\smb\Software\AirtestIDE_2019-01-15_py3_win64\poco\proxy.py", line 285, in click
    ret = self.poco.click(pos_in_percentage)
  File "D:\smb\Software\AirtestIDE_2019-01-15_py3_win64\poco\pocofw.py", line 248, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "D:\smb\Software\AirtestIDE_2019-01-15_py3_win64\poco\utils\airtest\input.py", line 65, in click
    touch(pos, duration=self.default_touch_down_duration)
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 256, in touch
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 83, in try_log_screen
  File "airtest\aircv\aircv.py", line 26, in imwrite
cv2.error: C:\projects\opencv-python\opencv\modules\imgcodecs\src\grfmt_base.cpp:139: error: (-10) Raw image encoder error: Empty JPEG image (DNL not supported) in function cv::BaseImageEncoder::throwOnEror
```

**相关截图**
![image](https://user-images.githubusercontent.com/23083411/52038368-0100bf80-256d-11e9-8f35-9e89e137341d.png)

**python 版本:** `python3.7`

**poco 版本:** `1.0.72`

**设备:**
 - 系统: Win10

**Comment by magicedy** [comment]
已解决，需要加上set_current(0)，因为重新运行U3D编辑器的时候dev已经变了，G.DEVICE_LIST也已经更新，只是G.DEVICE还没更新，需要set_current去更新下
