### ISSUE TITLE
windows7上远程连接ios12系统设备执行pcoco('测试').click()点击报错

### ISSUE THREAD

**Issue by AlwaysTerry** [AirtestProject/Poco#134]
**描述问题bug**
windows7上远程连接ios12系统设备执行pcoco('测试').click()点击报错

**截屏**

ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.25-py3.6.egg/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.25-py3.6.egg/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/iqiyi/Documents/airtest/func/scripts/qiyiTest.air/qiyiTest.py", line 14, in <module>
    poco("\u4f1a\u5458").click()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 313, in click
    pos_in_percentage = self.get_position(focus)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 594, in get_position
    pos = self.attr('pos')
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 715, in attr
    nodes = self._do_query(multiple=False)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 853, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/freezeui/hierarchy.py", line 89, in select
    return self.selector.select(query, multiple)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/sdk/Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/sdk/Selector.py", line 70, in getRoot
    return self.dumper.getRoot()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/ios/__init__.py", line 48, in dumpHierarchy
    data = ios_dump_json(jsonObj, self.size)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/ios/__init__.py", line 65, in ios_dump_json
    data = json_parser(jsonObj, screen_size)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/ios/__init__.py", line 75, in json_parser
    name = node["type"]
KeyError: 'type'

**Comment by weiyanfen** [comment]
> 已经解决需要ios设备开启https访问授权

你好，请问window7可以连接IOS进行自动化测试吗？需要弄啥？
