### ISSUE TITLE
poco辅助窗使用Android运行脚本，发生poco sdk的httpnanoserver无法启动以及airtest异常退出

### ISSUE THREAD

**Issue by HazelRunner** [AirtestProject/Poco#136]
**描述问题bug**
1.使用poco运行安卓app(框架选Android)
2.执行脚本时，页面静止无响应，随后报错，见下图
3.airtest软件自动退出
4.再次启动airtest软件，poco无法使用（点击poco录制按钮无响应），且poco Android UI元素树不显示
```
**脚本内容**
from airtest.core.api import *
auto_setup(__file__)
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

try:
    if poco(text="安逸").wait(1).exists():
        poco(text="安逸").click()
        touch(Template(r"tpl1550136749867.png", record_pos=(-0.431, -0.901), resolution=(1080, 2244)))
        assert_exists(Template(r"tpl1550134381543.png", record_pos=(0.005, 0.678), resolution=(1080, 2244)), "点击扫一扫按钮，进入二维码页面成功")
        keyevent("BACK")
    else:
        stop_app("com.minxing.client")
        start_app("com.minxing.client")
except AssertionError as e:
    print(e)

**运行日志**
"D:\python\python.exe" -u "D:\tool\AirtestIDE_2019-01-15_py3_win64\AirtestIDE_2019-01-15_py3_win64\sample\custom_launcher.py" "D:\airtest-runner-TFAnYi\2安逸模块用例集\TFAY_TXL_UI_001_扫一扫.air" --device Android://127.0.0.1:5037/CLB0218519005427 --log "D:/airtest\ecb8b739c989cae42ba391d6dc1498a8"
============================================================

	at com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:125)
	at com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:125)
	...
        com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:125)
	at com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:125)
	at com.netease.open.libpoco.sdk.Selector.selectImpl(Selector.java:95)
	at com.netease.open.libpoco.sdk.Selector.select(Selector.java:37)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:171)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:784)
        |--   Remote Traceback end   --|
Ran 1 test in 79.421s

FAILED (errors=1)
[10:10:06][DEBUG]<airtest.core.android.adb> D:\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s CLB0218519005427 forward --remove tcp:12456
[10:10:06][DEBUG]<airtest.core.android.adb> D:\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s CLB0218519005427 forward --remove tcp:19605
[Finished]
```
**复现步骤**
1.使用poco运行安卓app(框架选Android)
2.执行脚本时，页面静止无响应，随后报错，见下图
3.airtest软件自动退出
4.再次启动airtest软件，poco无法使用（点击poco录制按钮无响应），且poco Android UI元素树不显示

**预期效果**
在华为P20上正常使用poco运行脚本，无异常退出

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.6.5`

**操作系统:** `Windows10 64bit`

**设备:**
 - 型号: [EML-AL00]
 - 系统: [Android 8.1.0]
 - (别的信息)
 - 设备名称：[HUAWEI P20 ]

**其他相关环境信息**

**Comment by mackxu** [comment]
遇到相同问题，不是必现。
场景 用微信打开一个H5页面，检查页面上元素是否存在时报异常hrpc.exceptions.RpcRemoteException: java.lang.StackOverflowError: stack size 1036KB

File "E:\workspace\autoTest\webtv-test.air\utils\phone.py", line 23, in accountLogin
    if findText('账号登录').exists() is False:
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\proxy.py", line 774, in exists
    return self.attr('visible')
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\utils\retry.py", line 15, in wrapped
    return func(*args, **kwargs)
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\poco\utils\hrpc\hierarchy.py", line 33, in select
    return self.selector.select(query, multiple)
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\hrpc\object_proxy.py", line 92, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "E:\workspace\autoTest\webtv-test.air\venv\lib\site-packages\hrpc\client.py", line 81, in evaluate
    raise RpcRemoteException(resp)
hrpc.exceptions.RpcRemoteException: java.lang.StackOverflowError: stack size 1036KB

|--   Remote Traceback   --|

java.lang.StackOverflowError: stack size 1036KB
	at java.util.ArrayList.<init>(ArrayList.java:92)
	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:2697)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:2529)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:178)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:273)
	at android.view.accessibility.AccessibilityNodeInfo.getNodeForAccessibilityId(AccessibilityNodeInfo.java:3087)
	at android.view.accessibility.AccessibilityNodeInfo.getParent(AccessibilityNodeInfo.java:1354)
	at com.netease.open.libpoco.Node.getAttr(Node.java:109)
	at com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:115)
	at com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:137)
	at com.netease.open.libpoco.sdk.Selector.selectTraverse(Selector.java:137)

省略n行

        at com.netease.open.libpoco.sdk.Selector.selectImpl(Selector.java:107)
	at com.netease.open.libpoco.sdk.Selector.select(Selector.java:37)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:171)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:833)


|--   Remote Traceback end   --|
