### ISSUE TITLE
连接多台设备时，指定当前连接设备，poco的wait_for_appearance方法不能再指定设备执行

### ISSUE THREAD

**Issue by baobao01test** [AirtestProject/Poco#142]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
电脑连接多台手机终端时，通过connect_device指定当前连接设备，在执行wait_for_appearance时并不在当前终端执行
```
[10:02:20][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 shell dumpsys package com.netease.open.pocoservice
installed version is 39, installer version is 39. force_reinstall=False
[10:02:20][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[10:02:20][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 forward --no-rebind tcp:11423 tcp:10080
[10:02:20][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 forward --no-rebind tcp:12941 tcp:10081
[10:02:20][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 shell ps
[10:02:21][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 shell am force-stop com.netease.open.pocoservice
[10:02:21][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s RPG0118721000264 shell am start -n com.netease.open.pocoservice/.TestActivity
[10:02:21][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.ecustom tearDown
xe -s RPG0118721000264 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[pocoservice.apk] background daemon started.
[10:02:23][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s BBB0117901000292 wait-for-device
[10:02:23][DEBUG]<airtest.core.android.adb> C:\Python34\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s BBB0117901000292 shell getprop ro.build.version.sdk
111111111111111111111
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\airtest\cli\runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "C:\Python34\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python34\lib\site-packages\airtest\cli\runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\dev\workspace\AirtestAutoTest\script\test001.air\test001.py", line 15, in <module>
    poco("com.huawei.himovie:id/login_name").wait_for_appearance(30)
  File "C:\Python34\lib\site-packages\poco\proxy.py", line 631, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "com.huawei.himovie:id/login_name""

----------------------------------------------------------------------
Ran 1 test in 35.211s
```

**复现步骤**
当前电脑连接两台设备：BBB0117901000292、RPG0118721000264；BBB0117901000292设备当前页面有控件"com.huawei.himovie:id/login_name"，RPG0118721000264当前页面没有该控件
代码：
connect_device('Android:' + "BBB0117901000292")
print('111111111111111111111')
poco("com.huawei.himovie:id/login_name").wait_for_appearance(30)
poco("com.huawei.himovie:id/login_name").click()
print('2222222222222222222222')

**预期效果**
成功执行上诉语句

**相关截图**

**python 版本:** `Python 3.4.3`

**poco 版本:** `1.0.70`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [荣耀9青春版]
 - 系统: [安卓8.0]
 - (别的信息)

**其他相关环境信息**
必现

**Comment by mackxu** [comment]
关注，我也遇到同样问题

**Comment by yimelia** [comment]
请用set_current接口来确保当前设备是你心里期望的设备。

**Comment by mackxu** [comment]
> 请用set_current接口来确保当前设备是你心里期望的设备。

只有在使用poco时有问题，airtest 接口比如start_app都是正常的

**Comment by yimelia** [comment]
可以查一下poco的文档，连了不同手机时，要用不同的手机DEVICE实例去初始化poco，也就是说，2台手机可能要写两个poco对象，分别用2个手机来初始化，类似这样：
```
dev = connect_device('Android://<adbhost[localhost]>:<adbport[5037]>/<serialno>')
poco = AndroidUiautomationPoco(dev)
```

**Comment by guleng** [comment]
遇到了同样的问题，当前我是只连接一个手机，它好像有点加载控件时慢导致没有正常读取似的！我在poco辅助窗口注意到有时候加载的慢，得等一会儿才能出现。
