### ISSUE TITLE
PocoHierarchyViewer一直显示处理中

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#15]
os: win10 home
software:1.0.1:一直显示“处理中”
airtestIDE V0.0.14 显示正常
关闭airtestIDE 后，PocoHierarchyViewer 再重新打开；也是显示“处理中”

![2](https://user-images.githubusercontent.com/38519076/39339692-c1e4cd4c-49fc-11e8-82f2-f216727ce2d5.png)
![1](https://user-images.githubusercontent.com/38519076/39339715-d7e0a986-49fc-11e8-83c6-3b9c3c63a0d4.png)

**Comment by adolli** [comment]
麻烦在HierarchyViewer中回到主页，点一下右上角🔧(扳手)按钮，在弹出的控制台Console页里看下有无报错信息。谢谢

**Comment by bs111** [comment]
有的 

Unhandled rejection Error: Invalid filename
    at new ApkReader (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\node-apk-parser\lib\apkreader.js:27:17)
    at Function.ApkReader.readFile (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\node-apk-parser\lib\apkreader.js:16:14)
    at E (file:///D:/1_work/AutoTest/AirtestIDE/PocoHierarchyViewer-win32-x64/resources/app/lib/js-build/viewer/index.js:1:49688)
    at file:///D:/1_work/AutoTest/AirtestIDE/PocoHierarchyViewer-win32-x64/resources/app/lib/js-build/viewer/index.js:1:50290
    at tryCatcher (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (D:\1_work\AutoTest\AirtestIDE\PocoHierarchyViewer-win32-x64\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by adolli** [comment]
试试最新版的 [HierarchyViewer](http://poco.readthedocs.io/en/latest/source/doc/about-standalone-inspector.html)

**Comment by adolli** [comment]
fixed

**Comment by wyel2000** [comment]
Unhandled rejection Error: Invalid filename
    at new ApkReader (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\node-apk-parser\lib\apkreader.js:27:17)
    at Function.ApkReader.readFile (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\node-apk-parser\lib\apkreader.js:16:14)
    at E (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:59916)
    at file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:60518
    at tryCatcher (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by wyel2000** [comment]
GET http://127.0.0.1:10080/hierarchy net::ERR_CONNECTION_REFUSED
h._onFinish @ index.js:1
(anonymous) @ index.js:1
r.emit @ index.js:1
j @ index.js:1
S @ index.js:1
l.end @ index.js:1
h.end @ index.js:1
s.end @ index.js:1
e @ index.js:1
(anonymous) @ index.js:1
runCallback @ timers.js:651
tryOnImmediate @ timers.js:624
processImmediate @ timers.js:596
E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\debuggability.js:865 Unhandled rejection RequestError: TypeError: Failed to fetch
    at new r (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1704390)
    at s.l.callback (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1706267)
    at s.e.callback.t.callback [as _callback] (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1705709)
    at n._callback.n.callback.n.callback (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1729137)
    at s.r.emit (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:689196)
    at s.onRequestError (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1737619)
    at t.exports.r.emit (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:689196)
    at file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1865692
From previous event:
    at a.d [as _captureStackTrace] (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:292365)
    at a._resolveFromExecutor (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:327734)
    at new a (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:320025)
    at s.l.init (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1705553)
    at s.e.request.Request.init (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1703849)
    at new s (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1727444)
    at i (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1708885)
    at t.value (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:61981)
    at t.value (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:19390)
    at Object.r (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1487431)
    at r (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1428244)
    at Object.executeDispatchesInOrder (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1429283)
    at d (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1424842)
    at m (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1424968)
    at Array.forEach (native)
    at t.exports (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1533218)
    at Object.processEventQueue (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1426026)
    at r (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1487681)
    at Object.handleTopLevel [as _handleTopLevel] (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1487767)
    at a (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1488247)
    at r.perform (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1528773)
    at Object.batchedUpdates (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1484987)
    at Object.batchedUpdates (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1510472)
    at dispatchEvent (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:1489264)
printWarning @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\debuggability.js:865
formatAndLogError @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\debuggability.js:590
fireRejectionEvent @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\debuggability.js:615
Promise._notifyUnhandledRejection @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\debuggability.js:61
Async._drainQueue @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\async.js:138
Async._drainQueues @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\async.js:146
Async.drainQueues @ E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\bluebird\js\release\async.js:17
index.js:1 GET http://127.0.0.1:10080/screen_size net::ERR_CONNECTION_REFUSED
h._onFinish @ index.js:1
(anonymous) @ index.js:1
r.emit @ index.js:1
j @ index.js:1
S @ index.js:1
l.end @ index.js:1
h.end @ index.js:1
s.end @ index.js:1
e @ index.js:1
(anonymous) @ index.js:1
runCallback @ timers.js:651
tryOnImmediate @ timers.js:624
processImmediate @ timers.js:596
index.js:1 GET http://127.0.0.1:10080/screen?width=720 net::ERR_CONNECTION_REFUSED

**Comment by wyel2000** [comment]
Unhandled rejection Error: Invalid filename
    at new ApkReader (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\node-apk-parser\lib\apkreader.js:27:17)
    at Function.ApkReader.readFile (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\node-apk-parser\lib\apkreader.js:16:14)
    at E (file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:59916)
    at file:///E:/mpaas/PocoHierarchyViewer/resources/app/lib/js-build/viewer/index.js:1:60518
    at tryCatcher (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (E:\mpaas\PocoHierarchyViewer\resources\app\node_modules\adbkit\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
