### ISSUE TITLE
airtest拉起poco报错unable to launch AndroidUiautomationPoco

### ISSUE THREAD

**Issue by wallacegui** [AirtestProject/Poco#167]
[Start running..]
save log in 'C:\Users\jazminexu\AppData\Local\Temp\AirtestIDE\scripts\8b0b370809cb1320dc4377825b2319f6'
[12:27:17][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 wait-for-device
[12:27:17][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell getprop ro.build.version.sdk
[12:27:17][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys activity top
[12:27:17][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys package com.netease.nie.yosemite
[12:27:18][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell settings get secure default_input_method
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell ime list -a
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys package com.netease.open.pocoservice
installed version is 39, installer version is 39. force_reinstall=False
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 forward --no-rebind tcp:12492 tcp:10080
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 forward --no-rebind tcp:14734 tcp:10081
[12:27:18][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell ps
[12:27:19][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell am force-stop com.netease.open.pocoservice
[12:27:19][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell am start -n com.netease.open.pocoservice/.TestActivity
[12:27:20][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
E:\AirtestIDE_2019-01-15_py3_win64\poco\drivers\android\uiautomation.py:265: UserWarning: [pocoservice.apk] instrumentation test server process is no longer alive
  warnings.warn("[pocoservice.apk] instrumentation test server process is no longer alive")
[poco[pocoservice.apk] stdout: b''
service.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.still waiting for uiautomation ready.

[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[12:27:42][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 uninstall com.netease.open.pocoservice
[12:27:43][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys package com.netease.open.pocoservice
installed version is None, installer version is 39. force_reinstall=False
[12:27:43][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 install E:\AirtestIDE_2019-01-15_py3_win64\poco\drivers\android\lib\pocoservice-debug.apk
[12:27:43][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=True
[12:27:43][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 install -r E:\AirtestIDE_2019-01-15_py3_win64\poco\drivers\android\lib\pocoservice-debug-androidTest.apk
[12:27:45][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell am force-stop com.netease.open.pocoservice
[12:27:45][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell am start -n com.netease.open.pocoservice/.TestActivity
[12:27:46][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[12:28:08][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 6EJ4C18908002261 shell dumpsys activity top
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "E:\testTools\perf\airTest\Performance\videolite_8.air\videolite_8.py", line 13, in <module>
    poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
  File "E:\AirtestIDE_2019-01-15_py3_win64\poco\drivers\android\uiautomation.py", line 179, in __init__
    raise RuntimeError("unable to launch AndroidUiautomationPoco")
RuntimeError: unable to launch AndroidUiautomationPoco

----------------------------------------------------------------------
Ran 1 test in 51.395s

**Comment by ybsdegit** [comment]
同遇到该问题

**Comment by hchm** [comment]
这问题没人解决吗

**Comment by yimelia** [comment]
造成这种情况的可能原因有很多，可以尝试排查一下：
不要开网络代理
关闭所有类似uiautomator这样的工具
彻底卸载pocoservice.apk（总共有2个），然后手工重装一次（在poco的文件夹里有这2个apk）

**Comment by Germey** [comment]
源码修改：poco/drivers/android/uiautomation.py

```
print("still waiting for uiautomation ready.")
```

后面加一句：

```
self.adb_client.shell('am start -n {}/.TestActivity'.format(PocoServicePackage)) 
```
