### ISSUE TITLE
mac os下写好的poco脚本，不会执行，然后就报错了。

### ISSUE THREAD

**Issue by loneyao** [AirtestProject/Poco#171]
**描述问题bug**
写好的poco脚本，不会执行，然后就报错了。

```
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/Volumes/HD/tggcpoco.air/tggcpoco.py", line 18, in <module>
    poco("PlayBtn").click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 283, in click
    pos_in_percentage = self.get_position(focus)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 563, in get_position
    pos = self.attr('pos')
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 684, in attr
    nodes = self._do_query(multiple=False)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 819, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/freezeui/hierarchy.py", line 89, in select
    return self.selector.select(query, multiple)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/sdk/Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/sdk/Selector.py", line 70, in getRoot
    return self.dumper.getRoot()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/simplerpc.py", line 74, in wait
self.agent.update()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/transport/tcp/main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/transport/tcp/safetcp.py", line 39, in recv
    trunk = self.sock.recv(size)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**复现步骤**
写好的poco脚本，不会执行，然后就报错了。

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![QQ20190328-175727](https://user-images.githubusercontent.com/12229795/55148363-07817100-5183-11e9-9120-912af6419ff2.png)

**python 版本:** `python3.6.8`

**poco 版本:** `poco==0.96.5`

**设备:**
 - 型号: [e.g. 诺基亚 7plus]
 - 系统: [e.g. Android 9.0]
 - (别的信息)

**其他相关环境信息**
(其他环境没试。)

**Comment by loneyao** [comment]
File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest

这个不知道是从哪里来的

**Comment by yimelia** [comment]
先启动应用，等它初始化完之后，再运行到相关的poco语句

**Comment by guomochong** [comment]
你好，怎么解决的
