### ISSUE TITLE
Error in AirtestIDE20 \ poco \ sdk \ Selector.py

### ISSUE THREAD

**Issue by chelovekley** [AirtestProject/Poco#208]
**Describe the bug**
Exceptions are being processed at the time of another exception.
```
`[Start running..]
save log in 'C:/AirtestIDE20/AirtestLog\4291660d4891d5bc2ea0574442029ffa'
[rpc]connected
[rpc]connected
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\AirtestIDE20\poco\sdk\Selector.py", line 137, in selectImpl
    result = [self.selectImpl(cond, multiple, root, maxDepth, onlyVisibleNode, includeRoot)[i]]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "C:\Users\wazzapps_user\Desktop\untitled.air\untitled.py", line 23, in <module>
    merge(dnk)
  File "C:\Users\wazzapps_user\Desktop\untitled.air\untitled.py", line 18, in merge
    cat[i].focus('center').drag_to(cat[len(cat)-i-1], duration=0.2)
  File "C:\AirtestIDE20\poco\proxy.py", line 246, in __getitem__
    pos = uiobj.get_position()
  File "C:\AirtestIDE20\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\AirtestIDE20\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "C:\AirtestIDE20\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "C:\AirtestIDE20\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "C:\AirtestIDE20\poco\proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "C:\AirtestIDE20\poco\freezeui\hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "C:\AirtestIDE20\poco\sdk\Selector.py", line 78, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "C:\AirtestIDE20\poco\sdk\Selector.py", line 140, in selectImpl
    u'Query results index out of range. Index={} condition "{}" from root "{}".'.format(i, cond, root))
poco.sdk.exceptions.NoSuchTargetException: Query results index out of range. Index=1 condition "('and', (('attr=', ('texture', '0')),))" from root "<poco.freezeui.hierarchy.Node object at 0x0000023A147636D8>".

----------------------------------------------------------------------
Ran 1 test in 1.319s

FAILED (errors=1)
[Finished]`
```

**To Reproduce**
I use this script
`from poco.drivers.unity3d import UnityPoco
poco = UnityPoco()

dnk=poco(texture="0")
def merge(cat):
    from poco.drivers.unity3d import UnityPoco
    poco = UnityPoco()
    
    
    if len(cat) > 1:
        for i in range(0, len(cat)):
            cat[i].focus('center').drag_to(cat[len(cat)-i-1], duration=0.2)
            from poco.drivers.unity3d import UnityPoco 
            poco = UnityPoco()
        
        
merge(dnk)`

** Expected behavior **
Characters in the game must move to other similar characters.

** python version: ** `python3.6`

** poco version: ** `1.0.76`

** Smartphone (please complete the following information): **
On all the devices that I managed to use.
About 5 pieces

**Comment by yimelia** [comment]
hi @chelovekley 
Is it because when you drag and drop the "cats", the object list is also reduced, so that the corresponding object cannot be found?

**Comment by chelovekley** [comment]
@yimelia No, it is unlikely. It worked fine on AirtestIDE 1.2.0

**Comment by chelovekley** [comment]
Yes, in version 1.2.1 Such an error takes place.
I downloaded both versions from the site and there is no such problem in 1.2.0, the code is being successfully executed.

An error also comes out through the command line.
Tell me, how can I run Airtest 1.2.0 via the command line?

**Comment by chelovekley** [comment]
I loaded into the local environment
pip airtest == 1.0.20
pip pocoui == 1.0.70
And it all worked.
Please check it

**Comment by yimelia** [comment]
hi @chelovekley 
do you use your local environment python.exe?
![image](https://user-images.githubusercontent.com/6896468/58935341-d4b9b180-879f-11e9-81be-75ebdea19ab7.png)

in AirtestIDE1.2.0, we use pocoui==1.0.75
in AirtestIDE 1.2.1, pocoui==1.0.76

**Comment by chelovekley** [comment]
Yes, I use it like this
![image](https://user-images.githubusercontent.com/44580442/58936272-8e615400-8799-11e9-9296-915ea0eb52d4.png)

**Comment by yimelia** [comment]
if you're using the custom python path, it will use your python to run the script, I think it should be independent of the IDE version...

![image](https://user-images.githubusercontent.com/6896468/58937275-88bd3b80-87a4-11e9-8d4f-84d36e10642f.png)

if copy this line and run in your CMD, will it be ok?

**Comment by chelovekley** [comment]
If I install pocoui == 1.0.75
and run the specified lines from the different versions of AirtestIDE 1.2.0 and AirtestIDE 1.2.1 on the command line
then I get the same error.

If I install pocoui == 1.0.70
and then I run everything successfully
