### ISSUE TITLE
运行demo用例报错

### ISSUE THREAD

**Issue by gzhtest** [AirtestProject/Poco#219]
连接的是mumu模拟器
`import time
from poco.drivers.unity3d import UnityPoco

poco = UnityPoco()

poco('btn_start').click()
time.sleep(1.5)

shell = poco('shell').focus('center')
for star in poco('star'):
    star.drag_to(shell)
time.sleep(1)

assert poco('scoreVal').get_text() == "100", "score correct."
poco('btn_back', type='Button').click()`

详细报错如下
[06:21:28][DEBUG]<airtest.core.android.adb> F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/loc
al/tmp/minicap -i ; echo ---$?---
Traceback (most recent call last):
  File "testunityeditor.py", line 8, in <module>
    poco('btn_start').click()
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\poco\proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\poco\pocofw.py", line 252, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\poco\utils\airtest\input.py", line 63, in click
    pw, ph = self._get_touch_resolution()
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\poco\utils\airtest\input.py", line 54, in _get_touch_resolution
    return current_device().get_current_resolution()
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\core\android\android.py", line 560, in get_current_resolution
    w, h = self.display_info["width"], self.display_info["height"]
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\core\android\android.py", line 527, in display_info
    self._display_info = self.get_display_info()
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\core\android\android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\core\android\minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "D:\developtools\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\developtools\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\developtools\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[06:21:28][DEBUG]<airtest.core.android.adb> F:\code\UnityEditorWindow\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:7555 forward --remove tcp:18094

**Comment by yimelia** [comment]
mumu模拟器从某次更新开始，修改了一些底层接口，导致airtest无法支持了。目前最好换用别的模拟器，非常抱歉

**Comment by kanadeblisst** [comment]
夜神模拟器在外部环境出现类似的错误，但是在Airtest Ide中是可以运行的

**Comment by yimelia** [comment]
@kanadeblisst 
可能是你的命令行里漏了参数，参考这里：http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id10
