### ISSUE TITLE
Airtest ide连接iOS模拟器时没有自动安装PocoService 和Yosemite,有关输入的功能没办法跑，请问需要怎么解决

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/Poco#247]

**Comment by yimelia** [comment]
pocoservice和yosemite都是安卓下的
请具体描述你遇到的问题，贴出具体报错

**Comment by appp-deng** [comment]
> pocoservice和yosemite都是安卓下的
> 请具体描述你遇到的问题，贴出具体报错
就运行poco("TextField").set_text("18826054808”)时无法写入
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/gaokaozhitongche/test/login.air/login.py", line 13, in <module>
    poco("TextField").set_text("18826054808")
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 802, in set_text
    return self.setattr('text', text)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 761, in setattr
    raise InvalidOperationException('"{}" of "{}"'.format(str(e), self))
poco.exceptions.InvalidOperationException: "Unable to set attribute "text" of node "{'name': 'TextField', 'payload': {'isEnabled': '1', 'label': '', 'type': 'TextField', 'identifier': '', 'name': 'TextField', 'size': [0.855072463768116, 0.0625], 'pos': [0.5, 0.26450892857142855], 'zOrders': {'local': 0, 'global': 0}, 'anchorPoint': [0.5, 0.5], 'visible': True}, '__parent__': <poco.freezeui.hierarchy.Node object at 0x1185f3f98>}"." of "UIObjectProxy of "TextField""

**Comment by EraChen233** [comment]
我随意打开了一个iOS模拟器，型号试 iOS simulator 6s (12.2)，尝试在Safari浏览器输入，我这边可以正常运行哦
你是在什么app上试的呢？有在别的地方试过输入吗？
![image](https://user-images.githubusercontent.com/5961185/61852430-0facab80-aeec-11e9-8623-c848b7945319.png)

**Comment by appp-deng** [comment]
@EraChen233 我在走登录流程，需要输入账号和密码，在Android跑的时候用的是poco(name).set_text(),但是iOS好像不能这样用，还有看您的示例是直接text()，不用先定位吗？

**Comment by EraChen233** [comment]
这是个bug，先用airtest的text()方法替代一下吧

**Comment by bingosam** [comment]
@yimelia 
请问下这个BUG有排期修复吗？目前最新的版本1.0.87还没修复~~
另：iOS下get_text都是空的，取而代之的是value属性
![1350c3b1d1c903f950e1a1fa966ada3d](https://user-images.githubusercontent.com/20456289/169287731-c7a66da2-dc16-4240-b6d0-d7de0c8b3cf3.png)

**Comment by Ryaningli** [comment]
2023年了，催一下，wda都实现set_text，为什么poco不能实现的呢
