### ISSUE TITLE
poco断开连接后，不会自动重新连接

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#25]
使用powershell
建立连接 ，然后操作，插拔了手机和usb线的连接
还是会出现没有连接的情况
pip install -U pocoui
Requirement already up-to-date: pocoui in c:\python27\lib\site-packages (1.0.50)
window 10 basic

```
>>> containpoco.scroll(ordination)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 405, in scroll
    return self.focus(focus1).drag_to(self.focus(focus2), duration=duration)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 371, in drag_to
    target_pos = target.get_position()
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 507, in get_position
    x, y = self.attr('pos')
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "C:\Python27\lib\site-packages\poco\utils\hrpc\hierarchy.py", line 27, in select
    return self.selector.select(query, multiple)
  File "C:\Python27\lib\site-packages\hrpc\object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "C:\Python27\lib\site-packages\hrpc\client.py", line 64, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "C:\Python27\lib\site-packages\hrpc\transport\http.py", line 19, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "C:\Python27\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=18092): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003775278>: Failed to establish a new connection: [Errno 10061] ',))
>>>
```

**Comment by Meteorix** [comment]
确认下，这是在使用poco测试安卓源生应用吧？

**Comment by bs111** [comment]
是的 测试的是原生的应用

**Comment by Meteorix** [comment]
如果是在rpc请求的过程中断开，是会直接跑出错误的，你可以try catch住，然后加入重试机制

**Comment by bs111** [comment]
大神，请问这个重试机制，是指代什么。
是我继续使用后面的poco语句去执行下一条用例，还是指代其他，可以具体一点吗？

**Comment by adolli** [comment]
这个像是手机上的PocoService.apk挂掉了，try catch可能没用。下个版本尝试修复下。

**Comment by adolli** [comment]
fixed at `pocoui==1.0.67`. try to upgrade by `pip install -U pocoui`.
