### ISSUE TITLE
poco获取unity的BoxCollider组件坐标的取值范围大于[-1,1]，导致点击时提示超出屏幕

### ISSUE THREAD

**Issue by kappamaru** [AirtestProject/Poco#255]
**描述问题bug**
使用poco获取unity的BoxCollider组件坐标，得到的值为[-2.64066744, 0.450024962]
但屏幕的x和y坐标取值为[-1,1]，在点击上述组件时会提示坐标超出屏幕范围

```
Traceback (most recent call last):
  File "AirtestIDE.py", line 79, in <module>
  File "AirtestIDE.py", line 57, in main
  File "app\widgets\code_runner\tracer.py", line 72, in run_pyfile
  File "E:\AirtestIDE_2019-05-09\position.py", line 14, in <module>
    poco("building_summon|5673770611").focus([0.5,0.5]).click()
  File "E:\AirtestIDE_2019-05-09\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "E:\AirtestIDE_2019-05-09\poco\proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "E:\AirtestIDE_2019-05-09\poco\pocofw.py", line 251, in click
    raise InvalidOperationException('Click position out of screen. pos={}'.format(repr(pos)))
poco.exceptions.InvalidOperationException: Click position out of screen. pos=[-2.64066744, 0.450024962]
```

**复现步骤**
1. 在UI树中找到对应模型的节点（任意BoxCollider组件有三维坐标）
2. poco("building_1|5673770611").click()
3. See error

**预期效果**
希望能够点到对应的节点，或者用其他方法可以将该组件坐标移到屏幕中心

**python 版本:** `python3.6.5`
**poco 版本:** `1.0.76`

**设备:**
 - 型号: [ google Nexus 6]
 - 系统: [Android 7.0]

**Comment by TreHack** [comment]
最好不要用这种碰撞体作为元素去点击，碰撞体在游戏画面中一般不可见，且很多碰撞体的包围盒一般都很大，中心点很容易超出屏幕范围

**Comment by kappamaru** [comment]
> 最好不要用这种碰撞体作为元素去点击，碰撞体在游戏画面中一般不可见，且很多碰撞体的包围盒一般都很大，中心点很容易超出屏幕范围

因为游戏中的模型都是这种组件，如果不使用这个碰撞体的话，有没有推荐的方法可以去操作这类的模型呢？另外，请问poco是否支持使用反射？
