### ISSUE TITLE
脚本运行结束后报错 File "D:\Python36\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#270]
****
脚本运行结束后报错 File "D:\Python36\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__

```
[03:23:56][DEBUG]<airtest.core.android.adb> D:\Python36\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s CEZT4H85TWFQLZTG forward --remove tcp:19439
[03:23:56][DEBUG]<airtest.core.android.adb> D:\Python36\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s CEZT4H85TWFQLZTG forward --remove tcp:14460
[03:23:56][DEBUG]<airtest.core.android.adb> D:\Python36\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s CEZT4H85TWFQLZTG forward --remove tcp:18578
[03:23:56][DEBUG]<airtest.core.android.adb> D:\Python36\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s CEZT4H85TWFQLZTG forward --remove tcp:13184
[03:23:56][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@75840a7>'>
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
  File "D:\Python36\lib\site-packages\hrpc\client.py", line 63, in evaluate
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=14460): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001558FC84860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
  File "D:\Python36\lib\site-packages\hrpc\transport\http.py", line 26, in send

Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@c709954>'>
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
  File "D:\Python36\lib\site-packages\hrpc\client.py", line 63, in evaluate
[Finished]
  File "D:\Python36\lib\site-packages\hrpc\transport\http.py", line 26, in send
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=14460): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001558FAA1048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))


============================================================
```

**复现步骤**
1.anroid 9.0手机.
2.打开usbdebug，去stayawake中这个选项中，将它对应的开关打开。

**预期效果**
脚本执行正常。

**相关截图**

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

poco.device.adb.shell("am start -S -n com.android.settings/com.android.settings.Settings")
poco.scroll(direction='vertical',percent=0.8,duration=1.0)
poco(text="System").click()
poco(text="Advanced").click()
poco(text="Developer options").click()
#获取“Stay awake”的标签位置
StayawakeDesc=poco(type="android.widget.TextView",text="Stay awake")
if StayawakeDesc.exists():
    #去判断这个设备关联的开关项目的开关
    relatedRadioButton=StayawakeDesc.parent()\
        .sibling(resourceId="android:id/widget_frame")\
        .offspring(resourceId="android:id/switch_widget")
    if relatedRadioButton.exists():
        print(relatedRadioButton.get_position())
        checkState=relatedRadioButton.attr("checked")
        if checkState==False:
            #如果是关闭的，我们就打开它
            relatedRadioButton.click()

**python 版本:** `python3.6`

**poco 版本:** `1.0.76`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 9.0]
 - 系统: [e.g. WIin10]

**Comment by bs111** [comment]
![捕获2](https://user-images.githubusercontent.com/38519076/63496391-6a89f080-c4f4-11e9-91be-018e7a7958aa.PNG)
![捕获](https://user-images.githubusercontent.com/38519076/63496393-6bbb1d80-c4f4-11e9-940a-c1562cb1f818.PNG)

**Comment by bs111** [comment]
[打开USBdebug中的stayAwake.txt](https://github.com/AirtestProject/Poco/files/3528933/USBdebug.stayAwake.txt)

**Comment by renkchina** [comment]
我也是这个问题。请问怎么解决？

**Comment by summerAli** [comment]
遇到同样的问题
pycharm中运行脚本，脚本可以正常运行，测试结束后出现报错
[09:51:31][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@8c8b023>'>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\hrpc\client.py", line 63, in evaluate
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\hrpc\transport\http.py", line 26, in send
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=13044): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007720C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@ba2009b>'>
电脑 win 7  测试设备 安卓 9

**Comment by summerAli** [comment]
应该是有两个情况
1.没有遍历UI节点，对单个节点进行获取，并进行操作 
pop = poco("android:id/content").offspring("android.widget.LinearLayout").child(
        ....xx......  ).child("android.widget.LinearLayout")[0].child(
          .. xx ...)
    assert_equal(pop.exists(), True)   —— 这样写会报错
改成  pop = poco("android:id/content").offspring("android.widget.LinearLayout").child(
        ....xx......  ).child("android.widget.LinearLayout")[0].child(
          .. xx ...).exists()
assert_equal(pop, True)  —— 这样就可以了
包名有公司名，就用xx代替了 o(╯□╰)o 
2.脚本里面：先迭代遍历一组UI后，进行click(）点击操作；如果只跑一次，是正常的；如果进行循环测试，测试可以正常进行，但测试结束后会报错 。

**Comment by lingr7** [comment]
遇到了同样的问题。
