### ISSUE TITLE
ios中poco中的textMatches无法使用，不能用正则模糊匹配文本

### ISSUE THREAD

**Issue by qiujinle** [AirtestProject/Poco#294]
Ios12.2版本，使用poco(textMatches=".*一下.*").click()，报错

**复现步骤**
1. 手机打开safari浏览器，进入百度
2. 点击搜索框输入1
3. 执行代码
from airtest.core.api import *
from poco.drivers.ios import iosPoco
poco = iosPoco()
poco(textMatches=".*一下.*").click()
4. 错误日志log
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 26, in wrapped
    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 681, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "text matches .*一下.*""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "C:\Users\fairlink\Desktop\ios.air\ios.py", line 13, in <module>
    poco(textMatches=".*一下.*").click()
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 29, in wrapped
    raise e
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "C:\Users\fairlink\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text matches .*一下.*"

**预期效果**
可以匹配到百度一下，并且点击

**相关截图**

**python 版本:** `python3.6.8`

**poco 版本:** `1.0.78`

**设备:**
 - 型号: iphone8
 - 系统: ios12.2

**Comment by qiujinle** [comment]
![1](https://user-images.githubusercontent.com/44936424/66795900-95af2000-ef38-11e9-99d5-257092a890fa.png)
![2](https://user-images.githubusercontent.com/44936424/66795901-95af2000-ef38-11e9-8a50-50b32aac88d0.png)

**Comment by yimelia** [comment]
感谢反馈，我们检查一下这个问题

**Comment by MaNongXiaoGang** [comment]
Android也不行

**Comment by jsruth** [comment]
> 感谢反馈，我们检查一下这个问题

请问有进展了吗，Android貌似还是不好使
