### ISSUE TITLE
使用poco执行用例过程中概率出现错误socket.error("socket connection broken")

### ISSUE THREAD

**Issue by cinanji** [AirtestProject/Poco#297]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
用例在执行的时候会概率出现：socket.error("socket connection broken")。
时好时坏

```
Traceback (most recent call last):
  File "/Users/zyq/testlibrary/PocoLibrary/PocoKeywords.py", line 164, in get_text
    text = self.poco(location).get_text()
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 788, in get_text
    text = self.attr('text')
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Library/Python/2.7/site-packages/poco/freezeui/hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "/Library/Python/2.7/site-packages/poco/sdk/Selector.py", line 78, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/Library/Python/2.7/site-packages/poco/sdk/Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "/Library/Python/2.7/site-packages/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=20)
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/simplerpc.py", line 74, in wait
    self.agent.update()
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/transport/tcp/main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/transport/tcp/safetcp.py", line 42, in recv
    raise socket.error("socket connection broken")
```

**复现步骤**

**预期效果**
1. 想知道socket关闭都原因有哪些？
2. 如果出现这种错误要重启client 在代码里怎么调用

**相关截图**
![image](https://user-images.githubusercontent.com/18208159/66896053-c1103880-f026-11e9-930e-0844460f3b99.png)

**python 版本:** `python2.7`

**poco 版本:** `1.0.78`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 目前调试的三台设备都会随机出现这个问题，华为p6，vivoz1，oneplus 6

**其他相关环境信息**
macos 10.14.5

**Comment by yimelia** [comment]
时好时坏的话，可能有几种情况：
- USB线或者是USBHUB质量不够好，导致连接不够稳定，一旦出现抖动就会导致断开
- 部分手机上，可能因为有些设置导致手机会自动清理进程，把pocoservice进程给清理掉了，例如我们之前发现华为某些型号的手机助手会有这样的操作，参考[这里](https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_5)
- 某些低端手机内存很小，在运行到内存不足的情况下也有可能会清理掉非当前进程

第一种情况是概率最高的，很多连接问题其实都是USB质量问题
