### ISSUE TITLE
使用AndroidUiautomationPoco运行200+条用例报错，每次跑到100条pocoservice报错，如图所示

### ISSUE THREAD

**Issue by lizhouquan1017** [AirtestProject/Poco#300]
pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.still waiting for uiautomation ready.

still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
Exception ignored in: <function RpcObjectProxy.__del__ at 0x00000278EAE21378>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\transport\http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Exception ignored in: <function RpcObjectProxy.__del__ at 0x00000278EAE21378>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\transport\http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by yimelia** [comment]
请完善你的问题描述

**Comment by LRL2018** [comment]
我也遇到这个，测试脚本运行的时间久了，就会报你发的这个错误

**Comment by bs111** [comment]
我也遇到了，重复执行一条用例也会出现。
win10  1909
python 3.6
pocoui==1.0.80
airtest==1.1.6

[09:42:06][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am force-stop com.netease.open.pocoservice
[09:42:06][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:06][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:07][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am start -n 
com.netease.open.pocoservice/.TestActivity
[09:42:08][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:09][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[09:42:09][DEBUG]<airtest.core.android.adb> g:\MyPython_Phone\.venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 626a6878 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.

**Comment by keaizhang** [comment]
+1，有解决方式吗

**Comment by vividius** [comment]
please help on this.
