### ISSUE TITLE
回放时获取的UI元素，在脚本执行时候无法查找到

### ISSUE THREAD

**Issue by beansKingdom** [AirtestProject/Poco#301]
使用的airtest 自带的poco Assistant工具， 通过录制找到了如下UI路径：

```python
poco("android.widget.LinearLayout").offspring("com.chrome.dev:id/compositor_view_holder").offspring("root")[1].child("android.view.View")[4].click()
```

但是当我在代码里面使用的时候，却一直报超出了列表长度

**具体测试代码如下：**

```python
sleep(3)
parent_frame = poco("android.widget.LinearLayout").offspring("com.chrome.dev:id/compositor_view_holder").offspring("root")
print("test parent_frame: %s" % parent_frame)
print(type(parent_frame))
print(len(parent_frame))    # 此处一直返回长度是1，那做parent_frame[1]肯定超出长度？？

poco("android.widget.LinearLayout").offspring("com.chrome.dev:id/compositor_view_holder").offspring("root")[1].child("android.view.View")[4].click()
```

具体报错信息如下：

```bash
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/hly/Desktop/hlyDir/project/python/airtest_project/common_utils/testCommon.air/testCommon.py", line 138, in <module>
    mai_zeng_activity_operate("test", "test1")
  File "/Users/hly/Desktop/hlyDir/project/python/airtest_project/common_utils/testCommon.air/testCommon.py", line 135, in mai_zeng_activity_operate
    poco("android.widget.LinearLayout").offspring("com.chrome.dev:id/compositor_view_holder").offspring("root")[1].child("android.view.View")[4].click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 250, in __getitem__
    return self._sorted_children[item][0]
IndexError: list index out of range
```

**Comment by yimelia** [comment]
录制时的屏幕和回放时不一定完全相同，用自动生成的语句其实会很容易失败，试一下把`parent_frame`里面的所有元素print出来看看到底有多少个
