### ISSUE TITLE
使用pycharm执行完用例脚本之后总会提示hrpc.exceptions.TransportDisconnected

### ISSUE THREAD

**Issue by chenyuzhen233** [AirtestProject/Poco#303]
**描述问题bug**
使用unittest+airtest编写安卓自动化测试脚本。每次执行完用例脚本之后pycharm控制台总会提示HTTPConnectionPool。用例形如：进入微信聊天界面，发送消息，检查消息是否成功。用例执行成功后，pycharm控制台总会显示hrpc.exceptions.TransportDisconnected异常。

```
[11:32:34][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell settings get secure default_input_method
[11:32:34][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell ime list -a
[11:32:34][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell am broadcast -a ADB_INPUT_TEXT --es msg 'test'
[11:32:35][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell input keyevent ENTER
[11:32:40][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell input keyevent BACK
[11:32:41][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell input keyevent BACK
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:15663
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:16397
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:19483
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:17705
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:12157
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:17819
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:17439
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:13402
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:13877
[11:32:42][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception ignored in: <function RpcObjectProxy.__del__ at 0x000001585A005158>
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\client.py", line 63, in evaluate
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\transport\http.py", line 26, in send
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=17819): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001585A2AD780>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
```

**相关截图**
![image](https://user-images.githubusercontent.com/18247888/60232980-fa366880-98d0-11e9-8f12-0b6f3f7a49b4.png)

![image](https://user-images.githubusercontent.com/18247888/60233166-d889b100-98d1-11e9-8b70-356cc34b6869.png)

![image](https://user-images.githubusercontent.com/18247888/60233524-3cf94000-98d3-11e9-8439-b180b5c0729c.png)

**复现步骤**
1. 实在不知道怎么复现这个步骤，如果只是单个.air脚本运行就不会出现，但是多个.py脚本相互导包时就会出现这个问题。

**预期效果**
想要去掉这个异常报错信息。

**python 版本:** `python3.7.2`

**airtest 版本:** `1.0.27`

**设备:**
 - 型号 :小米 MIX 2S
 - 系统:  Android9

**其他相关环境信息**

**Comment by 812191338** [comment]
同样的问题。
但是我发现，设置了auto_setup(__file__, logdir="./log")会引发问题，auto_setup(__file__)就不会。

**Comment by 792607724** [comment]
@yimelia 
我这边能够稳定复现，代码如下：
"""
    wait():等待节点
    如下：等待gallery节点出现
"""
gallery_node = poco(name = "Gallery").wait(timeout = 10)
执行完即报出错误，麻烦帮忙看下，以便解决，很多语句单条执行都会报这个错误，使用的Pycharm
![image](https://user-images.githubusercontent.com/39899119/99875204-b318e800-2c28-11eb-90bf-bc4d483accc3.png)
复现步骤
gallery_node = poco(name = "Gallery").wait(timeout = 10)
单条代码执行，去wait等待Gallery节点，执行完即报错hrpc.exceptions.TransportDisconnected
预期效果
想要去掉这个异常报错信息。

python 版本: Python 3.7.4
airtest 版本: Version: 1.1.6
poco版本:Version: 1.0.80
设备:
型号 :华为P30 Pro
系统: Android10

**Comment by myloadrunner** [comment]
有解决吗，我现在也出现这个问题了

**Comment by 792607724** [comment]
请问有解决吗

**Comment by 792607724** [comment]
@yimelia 请问该问题有解决吗，谢谢
