### ISSUE TITLE
poco操作元素时报错：json.decoder.JSONDecodeError: 

### ISSUE THREAD

**Issue by choicepython** [AirtestProject/Poco#312]
**poco**

**描述问题bug**
(使用airtest .py脚本操作页面元素报json错误，.air脚本操作正常)

```
（
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 58, in main
  File "app\widgets\code_runner\tracer.py", line 72, in run_pyfile
  File "C:\Users\admin\Desktop\抖音\douyin1.py", line 20, in <module>
    poco("抖音短视频").click()
  File "D:\Program Files\AirTestIDE\AirtestIDE_2019-09-11_py3_win64\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\Program Files\AirTestIDE\AirtestIDE_2019-09-11_py3_win64\poco\proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "D:\Program Files\AirTestIDE\AirtestIDE_2019-09-11_py3_win64\poco\pocofw.py", line 252, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "D:\Program Files\AirTestIDE\AirtestIDE_2019-09-11_py3_win64\poco\utils\airtest\input.py", line 76, in click
    pos = self.get_target_pos(x, y)
  File "D:\Program Files\AirTestIDE\AirtestIDE_2019-09-11_py3_win64\poco\utils\airtest\input.py", line 54, in get_target_pos
    offsetx, offsety, pw, ph = self._get_touch_resolution()
  File "D:\Program Files\AirTestIDE\AirtestIDE_2019-09-11_py3_win64\poco\utils\airtest\input.py", line 66, in _get_touch_resolution
    w, h = current_device().get_current_resolution()
  File "airtest\core\android\android.py", line 560, in get_current_resolution
  File "airtest\core\android\android.py", line 527, in display_info
  File "airtest\core\android\android.py", line 546, in get_display_info
  File "airtest\utils\snippet.py", line 106, in ready_func
  File "airtest\core\android\minicap.py", line 149, in get_display_info
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
）
```

**复现步骤**

# -*- encoding=utf8 -*-
__author__ = "admin"

from airtest.core.api import *

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
from airtest.cli.parser import cli_setup

if not cli_setup():
    auto_setup(__file__, logdir=None, devices=[
            "Android:///",
    ])

# script content
print("start...")

poco("抖音短视频").click()

**预期效果**
(能够成功进入页面，并获得页面中的相关元素)

**相关截图**
(
![image](https://user-images.githubusercontent.com/54730231/69133852-856b0180-0af1-11ea-8443-4704e52240c1.png)
![image](https://user-images.githubusercontent.com/54730231/69133891-97e53b00-0af1-11ea-9b55-b24085cbd38d.png)
![image](https://user-images.githubusercontent.com/54730231/69133919-aa5f7480-0af1-11ea-8214-9066e8979cb2.png)
![image](https://user-images.githubusercontent.com/54730231/69133986-c6fbac80-0af1-11ea-8a0c-56bd34efcfd8.png)

)

**python 版本:** `python3.6`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [夜神模拟器]
 - 系统: [ Android 5.1.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
参考文档 https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2
