### ISSUE TITLE
 return cls._result_emitters.get(name) AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#32]
测试环境：
Win10 +myTestFlow
出现错误。
```
======================================================================
ERROR: setUpClass (__main__.TCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WebSafe\my-testflow\testflow\lib\case\android_app.py", line 21, in setUpClass
    meta_info_emitter = cls.get_result_emitter('metaInfo')
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\case.py", line 144, in get_result_emitter
    return cls._result_emitters.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by bs111** [comment]
file

**Comment by bs111** [comment]
[TF_TranslateAI_Launcher.zip](https://github.com/AirtestProject/Poco/files/2089415/TF_TranslateAI_Launcher.zip)
文件

**Comment by bs111** [comment]
[TF_TranslateAI_Launcher.zip](https://github.com/AirtestProject/Poco/files/2089470/TF_TranslateAI_Launcher.zip)
文件如下

**Comment by bs111** [comment]
忽略 不是问题，父类的init方法没有调用。
乌龙了
