### ISSUE TITLE
Python 3.7.0 调用poco出现以下错误

### ISSUE THREAD

**Issue by Ujmin** [AirtestProject/Poco#340]
Exception ignored in: <function RpcObjectProxy.__del__ at 0x00000242C1D00D08>
Traceback (most recent call last):
  File "D:\Program Files\Python\Python37\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
  File "D:\Program Files\Python\Python37\lib\site-packages\hrpc\client.py", line 63, in evaluate
  File "D:\Program Files\Python\Python37\lib\site-packages\hrpc\transport\http.py", line 23, in send
  File "D:\Program Files\Python\Python37\lib\site-packages\requests\api.py", line 116, in post
  File "D:\Program Files\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
  File "D:\Program Files\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
  File "D:\Program Files\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
  File "D:\Program Files\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
  File "F:\Python37\lib\site-packages\urllib3\connectionpool.py", line 588, in urlopen
  File "F:\Python37\lib\site-packages\urllib3\connectionpool.py", line 248, in _get_conn
  File "F:\Python37\lib\site-packages\urllib3\connectionpool.py", line 205, in _new_conn
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 1320, in debug
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 1468, in _log
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 1478, in handle
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 1540, in callHandlers
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 854, in handle
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 1080, in emit
  File "D:\Program Files\Python\Python37\lib\logging\__init__.py", line 1070, in _open
NameError: name 'open' is not defined

**Comment by yimelia** [comment]
有一定的可能性是你的Python环境可能有损坏，报错的库是logging，是否是混用了不同版本的python？

可能的参考链接：
https://bugs.python.org/issue26789
https://github.com/python-telegram-bot/python-telegram-bot/issues/1563

或者，请提供更多详细的信息方便我们定位问题：什么类型的Poco？运行了什么脚本语句？用了什么型号手机？

**Comment by Ujmin** [comment]
在del中直接使用open方法，或者del调用的函数中使用了open方法，好像就会报这个错误
根据错误提示来看，是 hrpc\object_proxy.py 的del 方法中调用的函数用到了open

**Comment by yimelia** [comment]
请提供更多详细的信息方便我们定位问题：什么类型的Poco？运行了什么脚本语句？用了什么型号手机？
