### ISSUE TITLE
OPPO 安装界面无法获取控件信息

### ISSUE THREAD

**Issue by HBoPRC** [AirtestProject/Poco#342]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
OPPO手机在安装 apk 过程进入如图所示界面时，无法获取界面控件；IDE也无法读取

```python
pprint(poco.agent.hierarchy.dump())
```

```
Traceback (most recent call last):
  File "D:/SVNProject/ceshi/AT/test/poco_test.py", line 11, in <module>
    pprint(poco.agent.hierarchy.dump())
  File "C:\Users\HBoPRC\AppData\Local\Programs\Python\Python37\lib\site-packages\poco\utils\retry.py", line 15, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\HBoPRC\AppData\Local\Programs\Python\Python37\lib\site-packages\poco\utils\hrpc\hierarchy.py", line 37, in dump
    return self.dumper.dumpHierarchy()
  File "C:\Users\HBoPRC\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\object_proxy.py", line 92, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "C:\Users\HBoPRC\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\client.py", line 81, in evaluate
    raise RpcRemoteException(resp)
hrpc.exceptions.RpcRemoteException: com.netease.open.libpoco.sdk.exceptions.NodeHasBeenRemovedException: Node was no longer alive when query attribute "visible". Please re-select.

|--   Remote Traceback   --|

com.netease.open.libpoco.sdk.exceptions.NodeHasBeenRemovedException: Node was no longer alive when query attribute "visible". Please re-select.
	at com.netease.open.libpoco.Node.getAttr(Node.java:81)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchyImpl(AbstractDumper.java:42)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchyImpl(AbstractDumper.java:43)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchyImpl(AbstractDumper.java:43)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchyImpl(AbstractDumper.java:43)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchyImpl(AbstractDumper.java:43)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchy(AbstractDumper.java:24)
	at com.netease.open.libpoco.sdk.AbstractDumper.dumpHierarchy(AbstractDumper.java:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:171)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:764)


|--   Remote Traceback end   --|
```

**预期效果**
安装过程能正常获取界面控件信息

**相关截图**
![QQ图片20200120144800](https://user-images.githubusercontent.com/37980474/72704916-f338b580-3b94-11ea-877c-d598428b48d7.png)

**python 版本:** `python3.7.3`

**poco 版本:** `1.0.79`

**设备:**
 - 型号: [e.g. OPPO R15]
 - 系统: [e.g. ColorOS 6.0.1(Android 9)]

**其他相关环境信息**
使用另外的 uiautomator2 可以在这个界面得到控件信息

**Comment by zhulinhyq** [comment]
这个问题啥时候能解决呢 @yimelia
