### ISSUE TITLE
connet timeout

### ISSUE THREAD

**Issue by saberloki** [AirtestProject/Poco#35]
经常会出现连接超时的问题，不管是用airtest命令行执行还是直接调用py文件
```
error log>>>:
<poco.utils.simplerpc.transport.tcp.asynctcp.Client localhost:16667 at 0xb1a30c8> is connected
[10:37:15][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --no-rebind tcp:13930 tcp:5001
waiting for connection...1
Connecting to host at: ('localhost', 13930)
<poco.utils.simplerpc.transport.tcp.asynctcp.Client at 0xb1a3b48> is connected
LOOP_THREAD ALREADY STARTED: <LoopThread(simplerpc_update, started daemon 8052)>
waiting for connection...0
waiting for connection...1
waiting for connection...2
waiting for connection...3
waiting for connection...4
waiting for connection...5
waiting for connection...6
waiting for connection...7
waiting for connection...8
waiting for connection...9
Traceback (most recent call last):
  File "D:/HCR����/��������-�����/�Զ������/Scrips/Skin.air/Skin.py", line 16, in <module>
    from Common.Gm import *
  File "D:\HCR����\��������-�����\�Զ������\Scrips\Common\Gm.py", line 15, in <module>
    from Common.CommonUI import *
  File "D:\HCR����\��������-�����\�Զ������\Scrips\Common\CommonUI.py", line 6, in <module>
    poco = UnityPoco()
  File "C:\Python27\lib\site-packages\poco\drivers\unity3d\unity3d_poco.py", line 56, in __init__
    super(UnityPoco, self).__init__(addr[1], dev, **options)
  File "C:\Python27\lib\site-packages\poco\drivers\std\__init__.py", line 88, in __init__
    agent = StdPocoAgent((ip, port))
  File "C:\Python27\lib\site-packages\poco\drivers\std\__init__.py", line 29, in __init__
    self.c.wait_connected()
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\rpcclient.py", line 58, in wait_connected
    raise RuntimeError("connecting timeout")
RuntimeError: connecting timeout
[10:37:20][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:14566
[10:37:20][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:16667
[10:37:20][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:13930
<LoopThread(simplerpc_update, started daemon 8052)> finished
```

**Comment by Meteorix** [comment]
Unity内的poco是你自己接入的吗？超时的时候可以确认下里面的server是否启动了，比如游戏是否启动、端口有没有listen之类的，需要debug一下

**Comment by saberloki** [comment]
@Meteorix 我自己接的
这个超时的问题，只是会比较频繁的出现，上周的时候还没有频繁的这个问题
怎么dubug，我只是个测试..

还有app重启后poco连接不上的问题修复了么，我重新实例化poco也连接不上，不知道啥问题..

errorlog>>>:
[11:11:43][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --no-rebind tcp:15857 tcp:5001
Connecting to host at: ('localhost', 15857)
LOOP_THREAD ALREADY STARTED: <LoopThread(simplerpc_update, started daemon 1792)>
waiting for connection...0
<poco.utils.simplerpc.transport.tcp.asynctcp.Client localhost:15857 at 0xabd04c8> is connected
waiting for connection...1
Traceback (most recent call last):
  File "D:/HCR����/��������-�����/�Զ������/Scrips/Skin.air/Skin.py", line 215, in <module>
    NewAutoTest = Skin()
  File "D:/HCR����/��������-�����/�Զ������/Scrips/Skin.air/Skin.py", line 29, in __init__
    self.welfare()
  File "D:\HCR����\��������-�����\�Զ������\Scrips\Common\CommonUI.py", line 143, in welfare
    self.buttonclick(poco("btn_welfare"))
  File "D:\HCR����\��������-�����\�Զ������\Scrips\Common\CommonUI.py", line 15, in buttonclick
    if self.button.exists():
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 659, in exists
    return self.attr('visible')
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "C:\Python27\lib\site-packages\poco\freezeui\hierarchy.py", line 89, in select
    return self.selector.select(query, multiple)
  File "C:\Python27\lib\site-packages\poco\sdk\Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "C:\Python27\lib\site-packages\poco\sdk\Selector.py", line 70, in getRoot
    return self.dumper.getRoot()
  File "C:\Python27\lib\site-packages\poco\freezeui\hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\simplerpc.py", line 76, in wait
    raise RuntimeError("%s timeout error" % self)
RuntimeError: <poco.utils.simplerpc.simplerpc.Callback object at 0x000000000AC51FD0> timeout error
[11:12:13][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:18444
[11:12:13][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:15262
[11:12:13][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:13642
[11:12:13][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:18458
[11:12:13][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 57e5b1d4 forward --remove tcp:15857
[11:12:13][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
<LoopThread(simplerpc_update, started daemon 1792)> finished

**Comment by saberloki** [comment]
@Meteorix 游戏一直是启动状态

**Comment by saberloki** [comment]
@Meteorix 
超时的问题我定位到了，启动多个pocoserver的时候，后面启动的pocoserver就容易连接超时

**Comment by Meteorix** [comment]
ok 多谢反馈，我们会优化一下poco的断线重连

**Comment by adolli** [comment]
@saberloki 我们最近已经优化了网络模块，可以尝试将poco更新到最新版，poco-sdk不需要更新。
另外你说的启动多个pocoserver，是在同一个游戏里启动多个poco-sdk的server吗？
