### ISSUE TITLE
连续测试，部分测试案例异常

### ISSUE THREAD

**Issue by lijinhua163** [AirtestProject/Poco#37]
运行环境:  centos 7，  shell脚本启动python， shell脚本内容（运行测试脚本前后添加启动app、关闭app命令）
adb -s $device shell am force-stop $package
adb -s $device shell am start -n $package/$activity
python -m airtest run /export/home/pwtestsvn/xtest/PwTestCase/pwrd/$game/$testcase --device $platform://$ip:$port/$device --log $logDir
adb -s $device shell am force-stop $package

问题描述：连续多次运行同一脚本，部分测试案例失败，报如下错误。 去掉重启app过程，则正常运行

[11:31:21][DEBUG]<airtest.core.android.adb> /export/home/pwtestenv/python3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s Q8W0215215006810 wait-for-device
[11:31:21][DEBUG]<airtest.core.android.adb> /export/home/pwtestenv/python3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s Q8W0215215006810 shell getprop ro.build.version.sdk
[11:31:21][DEBUG]<airtest.utils.logwraper> main_script: {'script': '/export/home/pwtestsvn/xtest/PwTestCase/pwrd/qyz/brun6.test.air'}
[11:31:21][DEBUG]<airtest.core.android.adb> /export/home/pwtestenv/python3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s Q8W0215215006810 forward --no-rebind tcp:14414 tcp:5001
E
======================================================================
ERROR: setUpClass (airtest.cli.runner.MyTestCase)
----------------------------------------------------------------------                                   
Traceback (most recent call last):
  File "/export/home/pwtestsvn/xtest/PwTestCase/pwrd/qyz/brun6.test.air/brun6.test.py", line 19, in setUpClass
    cls.poco = UnityPoco()                                                                               
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site-packages/poco/drivers/unity3d/unity3d_poco.py", line 56, in __init__
    super(UnityPoco, self).__init__(addr[1], dev, **options)
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site-packages/poco/drivers/std/__init__.py", line 90, in __init__
    agent = StdPocoAgent((ip, port))
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site-packages/poco/drivers/std/__init__.py", line 29, in __init__
    self.c.wait_connected()                                                                              
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site-packages/poco/utils/simplerpc/rpcclient.py", line 57, in wait_connected
    raise RuntimeError("Connection Closed")
RuntimeError: Connection Closed

----------------------------------------------------------------------                                   
Ran 0 tests in 0.627s                                                                                    
  
FAILED (errors=1)
====================================================================== 
ERROR: runTest (airtest.cli.runner.AirtestCase)                                                          
----------------------------------------------------------------------                                   
Traceback (most recent call last):
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/export/home/pwtestsvn/xtest/PwTestCase/pwrd/qyz/brun6.test.air/brun6.test.py", line 49, in <module>
    pocounit.main()
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site-packages/pocounit/__init__.py", line 48, in main
    exit(-1)
  File "/export/home/pwtestenv/python3.6/lib/python3.6/site.py", line 403, in __call__                   
    raise SystemExit(code)
SystemExit: -1

----------------------------------------------------------------------
Ran 1 test in 0.799s
 
FAILED (errors=1)
[11:31:21][DEBUG]<airtest.core.android.adb> /export/home/pwtestenv/python3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s Q8W0215215006810 forward --remove tcp:14414

**Comment by lijinhua163** [comment]
感谢解答！！
 Airtest/airtest/core/android/adb.py  1115 行 self.shell(['am', 'start', '-n', '%s/%s.%s' % (package, package, activity)])
我们的包 和 activity是完全不同的，比如 包名是com.company.project.channel1, channel2, 而activity是固定(com.company.project.MainActivity),和上面代码拼凑起来就错了。
我自己修改为 self.shell(['am', 'start', '-n', '%s/%s' % (package, activity)])
小问题哈

**Comment by Meteorix** [comment]
👍
