### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#39]
```
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of com.netease.open.libpoco.Node@c2100c1>'>
Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\hrpc\object_proxy.py", line 110, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\hrpc\client.py", line 64, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\hrpc\transport\http.py", line 19, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
```

**Comment by bs111** [comment]
win10系统

**Comment by adolli** [comment]
能麻烦提供一下你所使用的手机的信息吗？型号和系统版本

**Comment by bs111** [comment]
nexus 5 
8.1系统 OPM3.171019.016

**Comment by adolli** [comment]
#40

**Comment by adolli** [comment]
fixed at `pocoui==1.0.67`. try to upgrade by `pip install -U pocoui`.
