### ISSUE TITLE
win10 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#40]
"Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "d:\python36\Lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "d:\python36\Lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "d:\python36\Lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "d:\python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by bs111** [comment]
D:\WebSafe\AndroidTest\venv3\Lib\site-packages\airtest\core\android\static\adb\windows>adb version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as D:\WebSafe\AndroidTest\venv3\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe

C:\Users\xxx>adb version
Android Debug Bridge version 1.0.40
Version 4797878
Installed as C:\Users\borla\AppData\Local\Android\Sdk\platform-tools\adb.exe

**Comment by bs111** [comment]
EED:\WebSafe\AndroidTest\venv3\lib\site-packages\pocounit\case.py:204: UserWarning: Fail to stop result emitter: "SiteSnapshot". You can report this error to the developers or just ignore it. Error message: 
"Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "d:\python36\Lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\python36\Lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\python36\Lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\python36\Lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\python36\Lib\http\client.py", line 964, in send
    self.connect()
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connection.py", line 196, in connect
    conn = self._new_conn()
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C26AC0E978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=14136): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C26AC0E978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\pocounit\case.py", line 200, in run
    emitter.stop()
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\pocounit\result\site_snapshot.py", line 32, in stop
    self.snapshot('caseEnd')
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\pocounit\result\site_snapshot.py", line 38, in snapshot
    self.snapshot_screen(site_id)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\pocounit\result\site_snapshot.py", line 60, in snapshot_screen
    b64img, fmt = self.poco.snapshot()
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\poco\pocofw.py", line 418, in snapshot
    return self.agent.screen.getScreen(width)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\poco\drivers\android\uiautomation.py", line 78, in getScreen
    b64img = self.screen.getScreen(width)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\hrpc\object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\hrpc\client.py", line 64, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\hrpc\transport\http.py", line 19, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "D:\WebSafe\AndroidTest\venv3\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=14136): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C26AC0E978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

**Comment by adolli** [comment]
请换回1.0.39版的adb再试一下，另外看这个现象可能有以下两种原因
1. usb线质量不行，松动导致adb forward失效
2. 手机权限太高，自动把后台PocoService杀掉了

**Comment by bs111** [comment]
还是存在错误 都切换为39了
usb线也换过了

**Comment by bs111** [comment]
3.手机权限太高，自动把后台PocoService杀掉了
这个 可以搜索什么样的关键字吗

**Comment by adolli** [comment]
我看你的是nexus，手机权限这个一般在安全菜单或者开发者选项里面调一下。但是也不排除是OPM系统的问题，你有试过release版的系统吗？

**Comment by zuobian1234** [comment]
win 10 系统，连接的windows程序（unity打包成的pc版本），脚本执行完，游戏界面会弹出错误：
SocketException: 远程主机强迫关闭了一个现有的连接。
 || System.Net.Sockets.Socket+SocketAsyncResult.CheckIfThrowDelayedException ()
System.Net.Sockets.Socket.EndReceive (IAsyncResult asyncResult, System.Net.Sockets.SocketError& errorCode)
System.Net.Sockets.Socket.EndReceive (IAsyncResult result)
System.Net.Sockets.NetworkStream.EndRead (IAsyncResult ar)
Rethrow as IOException: EndRead failure
System.Net.Sockets.NetworkStream.EndRead (IAsyncResult ar)
TcpServer.AsyncTcpServer.HandleDatagramReceived (IAsyncResult ar) (at D:/ayemao/develop/project/client/Assets/Unity3D/TcpServer.cs:303)
UnityEngine.Debug:LogException(Exception)
TcpServer.AsyncTcpServer:HandleDatagramReceived(IAsyncResult) (at D:/ayemao/develop/project/client/Assets/Unity3D/TcpServer.cs:305)
System.Net.Sockets.Worker:Receive()
