### ISSUE TITLE
运行poco().click报错， 但是单独在airtestIDE跑这段语句正常

### ISSUE THREAD

**Issue by kagamimoe** [AirtestProject/Poco#43]
报错信息：
Error
Traceback (most recent call last):
  File "C:\sgame\scripts\test002.py", line 31, in test_change_name
    poco("imgHead").click()
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 283, in click
    pos_in_percentage = self.get_position(focus)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 499, in get_position
    pos = self.attr('pos')
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "C:\Python27\lib\site-packages\poco\proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "C:\Python27\lib\site-packages\poco\freezeui\hierarchy.py", line 89, in select
    return self.selector.select(query, multiple)
  File "C:\Python27\lib\site-packages\poco\sdk\Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "C:\Python27\lib\site-packages\poco\sdk\Selector.py", line 70, in getRoot
    return self.dumper.getRoot()
  File "C:\Python27\lib\site-packages\poco\freezeui\hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\simplerpc.py", line 72, in wait
    self.agent.update()
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\rpcclient.py", line 61, in update
    data = self.conn.recv()
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\transport\tcp\main.py", line 32, in recv
    msg_bytes = self.c.recv()
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\transport\tcp\safetcp.py", line 39, in recv
    trunk = self.sock.recv(size)
error: [Errno 10053] 

下面是代码：

```
device = connect_device("Android:///")
poco = StdPoco(15004, device)

class test002(unittest.TestCase):

    def setUp(self):
        print "开始启动游戏"
        normal_start()

    def test_change_name(self):
        sleep(10.0)
        # open_setting_panel()
        if poco("imgHead").exists:
            print("点击设置按钮")
            poco("imgHead").click()
            sleep(2.0)
        touch(Template(pic_dir_setting + r"edit_name.png"))

   def tearDown(self):
        print "执行完毕了，现在关闭游戏"
        normal_exit()

if __name__ == '__main__':
    unittest.main()

```

但是单独在airtestIDE里 ，运行这段报错代码是正常的 。

```
if poco("imgHead").exists:
            print("点击设置按钮")
            poco("imgHead").click()
            sleep(2.0)
```

**Comment by Meteorix** [comment]
@kagamimoe 你好，poco可以先回退一个版本试试``pip install -U pocoui=1.0.56``

**Comment by Meteorix** [comment]
可以尝试在启动游戏之后初始化poco：
```

class test002(unittest.TestCase):

    def setUp(self):
        print "开始启动游戏"
        normal_start()
        self.poco = StdPoco(15004, device)

```

**Comment by kagamimoe** [comment]
@Meteorix   poco回退到 1.0.56版本后 报另一个错误


```
Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.6\helpers\pycharm\utrunner.py", line 116, in <module>
    modules = [loadSource(a[0])]
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.6\helpers\pycharm\utrunner.py", line 40, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "C:\sgame\scripts\test002.py", line 12, in <module>
    from lib.common import normal_start,normal_exit,pic_dir_setting,return_panel,pic_dir
  File "C:\sgame\lib\common.py", line 16, in <module>
    poco = StdPoco(15004, device)
  File "C:\Python27\lib\site-packages\poco\drivers\std\__init__.py", line 93, in __init__
    agent = StdPocoAgent((ip, port))
  File "C:\Python27\lib\site-packages\poco\drivers\std\__init__.py", line 28, in __init__
    self.c.connect()
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\rpcclient.py", line 23, in connect
    self._wait_connected(timeout)
  File "C:\Python27\lib\site-packages\poco\utils\simplerpc\rpcclient.py", line 37, in _wait_connected
    raise RpcConnectionError("Rpc Connection Closed")
poco.utils.simplerpc.simplerpc.RpcConnectionError: Rpc Connection Closed
[10:48:19][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s ce12160cc43a001f0c forward --remove tcp:19378
```

**Comment by kagamimoe** [comment]
启动游戏之后初始化poco的话， 那在其他方法里怎么调用poco呢 

提示这个错误：
```
Error
Traceback (most recent call last):
  File "C:\sgame\scripts\test002.py", line 31, in test_change_name
    if poco("imgHead").exists:
NameError: global name 'poco' is not defined
```

**Comment by Meteorix** [comment]
这样你就可以 ``self.poco("imgHead").exists:``

**Comment by Meteorix** [comment]
或者你可以把poco设置为全局变量
```
poco = None

class test002(unittest.TestCase):

    def setUp(self):
        print "开始启动游戏"
        normal_start()
        global poco
        poco = StdPoco(15004, device)
```

**Comment by kagamimoe** [comment]
声明为全局变量后可以跑了。谢谢大佬
