### ISSUE TITLE
Poco查找元素获取属性进行变量赋值时，第一个进程OK，第二个进程执行后被Connect refuse

### ISSUE THREAD

**Issue by 792607724** [AirtestProject/Poco#432]
**(重要！问题分类)**
控件识别、树状结构、poco库报错
![Uploading image.png…]()

**描述问题bug**

trackback：
18575211714
18512026643
[01:52:09][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 shell input keyevent HOME
[01:52:10][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd shell am start -a android.intent.action.SENDTO -d sms:18575211714 --es sms_body Test
[01:52:10][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 shell am start -a android.intent.action.SENDTO -d sms:18512026643 --es sms_body Test
185 7521 1714 said, Test, 1 minute
('Test', '18575211714')
[01:52:14][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd forward --remove tcp:14619
[01:52:14][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd forward --remove tcp:19712
[01:52:14][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 forward --remove tcp:12953
[01:52:14][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 forward --remove tcp:15701
Process Process-20:
Traceback (most recent call last):
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x118b72310>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=15701): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118b72310>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/hrpc/transport/http.py", line 23, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=15701): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118b72310>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/run_test.py", line 121, in ui_task
    print(messaging_page.send_message(number))

代码报错路径：
### @  **File "/Users/cgt/PycharmProjects/AutomationProject/page/Messaging/messaging_page.py", line 29, in send_message
    receiver_content = self.poco("android:id/list").children()[2].get_name()**

  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/proxy.py", line 246, in __getitem__
    pos = uiobj.get_position()
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/proxy.py", line 735, in attr
    val = self.poco.agent.hierarchy.getAttr(nodes, name)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/utils/retry.py", line 20, in wrapped
    raise ex
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/utils/retry.py", line 15, in wrapped
    return func(*args, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/utils/hrpc/utils.py", line 36, in wrapped
    return func(self, nodes, name, *args, **kwargs)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/poco/utils/hrpc/hierarchy.py", line 24, in getAttr
    return self.attributor.getAttr(nodes, name)
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/hrpc/object_proxy.py", line 92, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/hrpc/client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/hrpc/transport/http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=15701): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118b72310>: Failed to establish a new connection: [Errno 61] Connection refused'))
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd forward --remove tcp:14619
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd forward --remove tcp:19712
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 forward --remove tcp:12953
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 forward --remove tcp:15701
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd forward --remove tcp:14619
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd forward --remove tcp:19712
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 forward --remove tcp:12953
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 forward --remove tcp:15701
Current device number is: 2
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 7c2440fd shell am force-stop com.netease.open.pocoservice
[01:52:23][DEBUG]<airtest.core.android.adb> /Users/cgt/PycharmProjects/AutomationProject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s b3e5b958 shell am force-stop com.netease.open.pocoservice

Process finished with exit code 0

**复现步骤**
    def send_message(self, number="1", content="Test"):
        self.device.shell("am start -a android.intent.action.SENDTO -d sms:%s --es sms_body %s" % (number, content))
        self.poco("com.google.android.apps.messaging:id/send_message_button_icon").wait().click()
        receiver_content = self.poco("android:id/list").children()[2].get_name()
        print(receiver_content)
        return content, number

**预期效果**
如复现步骤，当把self.poco("android:id/list").children()[2].get_name()赋给receiver_content后，第二个进程执行将会报错，第一个进程执行正常，不进行赋值操作，直接都调用self.poco("android:id/list").children()[2].get_name()则不会报错，两个进程运行正常，不知道是哪里都问题，是poco和进程之间没有设置好吗？

**python 版本:** `python3.7`

**poco 版本:** `pocoui==1.0.80`

**设备:**
 - 型号: [TCL 10SE]
 - 系统: [Android 11]

**Comment by 792607724** [comment]
已经找到原因，进程之间port串掉了，每台设备独立进程完成整个Pytest已实现批量测试
