### ISSUE TITLE
新版本1.2.7AirtestIDE 使用poco的swipe()报错

### ISSUE THREAD

**Issue by ouluyao** [AirtestProject/Poco#438]
**描述问题bug**
在1.2.7版本的AirtestIDE中使用类似poco("Windows").swipe([0,0.5])或者poco("xxx").swipe("down")的语句，执行会报以下错误：
TypeError：swipe() got an unexpected ketword argument 'steps'

log 信息：

[Start running..]
save log in '/var/folders/lm/l7d5y9413jb3qhcsxf9vltpr0000gn/T/AirtestIDE/scripts/6d84528f6304be23433ecd384c2b83f8'
custom setup
[03:31:43][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/conan/workspace/untitled.air/untitled.py", line 16, in <module>
    poco("Window").swipe([0,-0.5])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 459, in swipe
    ret = self.poco.swipe(origin, direction=dir_vec, duration=duration)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/pocofw.py", line 305, in swipe
    return self.agent.input.swipe(p1[0], p1[1], p2[0], p2[1], duration)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/airtest/input.py", line 89, in swipe
    swipe(pos, vector=direction, duration=duration, steps=steps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/api.py", line 437, in swipe
    G.DEVICE.swipe(pos1, pos2, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/ios/ios.py", line 33, in wrapper
    return func(self, *args, **kwargs)
TypeError: swipe() got an unexpected keyword argument 'steps'

custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 73, in runTest
    six.reraise(*sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/conan/workspace/untitled.air/untitled.py", line 16, in <module>
    poco("Window").swipe([0,-0.5])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 459, in swipe
    ret = self.poco.swipe(origin, direction=dir_vec, duration=duration)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/pocofw.py", line 305, in swipe
    return self.agent.input.swipe(p1[0], p1[1], p2[0], p2[1], duration)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/airtest/input.py", line 89, in swipe
    swipe(pos, vector=direction, duration=duration, steps=steps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/api.py", line 437, in swipe
    G.DEVICE.swipe(pos1, pos2, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/ios/ios.py", line 33, in wrapper
    return func(self, *args, **kwargs)
TypeError: swipe() got an unexpected keyword argument 'steps'

**预期效果**
可以使用poco进行滑动操作

**python 版本:** `python3.6`

**poco 版本:** `1.0.81`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号:iPhone XS
 - 系统: 12.0

**其他相关环境信息**
AirtestIDE 1.2.7 版本
在之前的版本都是正常的

**Comment by yimelia** [comment]
你本地的python环境里的airtest和pocoui都需要更新到最新版本

**Comment by ouluyao** [comment]
@yimelia  本地python环境里的airtest和pocoui也已经更新到了最新版本 仍然有这个问题

**Comment by yimelia** [comment]
把最新运行结果的报错再贴一次看看

**Comment by ouluyao** [comment]
[Start running..]
save log in '/var/folders/lm/l7d5y9413jb3qhcsxf9vltpr0000gn/T/AirtestIDE/scripts/6d84528f6304be23433ecd384c2b83f8'
[05:34:25][INFO]<airtest.core.ios.rotation> update orientation None->PORTRAIT
[05:34:25][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "airtest/cli/runner.py", line 70, in runTest
  File "/Users/conan/workspace/untitled.air/untitled.py", line 19, in <module>
    poco("Window").swipe("down")
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 459, in swipe
    ret = self.poco.swipe(origin, direction=dir_vec, duration=duration)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/pocofw.py", line 305, in swipe
    return self.agent.input.swipe(p1[0], p1[1], p2[0], p2[1], duration)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/airtest/input.py", line 89, in swipe
    swipe(pos, vector=direction, duration=duration, steps=steps)
  File "airtest/utils/logwraper.py", line 90, in wrapper
  File "airtest/core/api.py", line 437, in swipe
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 33, in wrapper
    return func(self, *args, **kwargs)
TypeError: swipe() got an unexpected keyword argument 'steps'

======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest/cli/runner.py", line 73, in runTest
  File "site-packages/six.py", line 703, in reraise
  File "airtest/cli/runner.py", line 70, in runTest
  File "/Users/conan/workspace/untitled.air/untitled.py", line 19, in <module>
    poco("Window").swipe("down")
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 459, in swipe
    ret = self.poco.swipe(origin, direction=dir_vec, duration=duration)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/pocofw.py", line 305, in swipe
    return self.agent.input.swipe(p1[0], p1[1], p2[0], p2[1], duration)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/airtest/input.py", line 89, in swipe
    swipe(pos, vector=direction, duration=duration, steps=steps)
  File "airtest/utils/logwraper.py", line 90, in wrapper
  File "airtest/core/api.py", line 437, in swipe
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 33, in wrapper
    return func(self, *args, **kwargs)
TypeError: swipe() got an unexpected keyword argument 'steps'

**Comment by yimelia** [comment]
这个是airtest接口的问题，将在下个版本修复，我先移动到airtest的issue列表中
