### ISSUE TITLE
RuntimeError: unable to launch AndroidUiautomationPoco

### ISSUE THREAD

**Issue by wanghehacker** [AirtestProject/Poco#44]
环境:
PC Windows 7
Android 8.0  OnePlus 3
`
poco、airtest、my-testflow都是clone的github上最新的版本，poco、airtest用pip install -e xxx命令安装，
执行my-testflow的example，报出以下错误：
```
E:\auto_test\my-testflow>python testflow\scripts\example.py
this testcase filename is "E:\auto_test\my-testflow\testflow\scripts\example.py"
.
using "C:\Python27\lib\site-packages" as project root. This testcase is "PocoTes
tSuite"
testcase locates in "C:\Python27\lib\site-packages\pocounit\suite.py"
using "E:\auto_test\my-testflow" as project root. This testcase is "CalculatorPl
us"
testcase locates in "E:\auto_test\my-testflow\testflow\scripts\example.py"
log filename will be "E:\auto_test\my-testflow\pocounit-results\testflow\scripts
\example\CalculatorPlus (customized name)\poco-result.log"
log filename will be "E:\auto_test\my-testflow\pocounit-results\testflow\scripts
\example\CalculatorPlus (customized name)\metainfo.txt"
[06:43:31][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe devices
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe devices
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e wait-for-device
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell getprop ro.build.version.sdk
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell cat /proc/cpuinfo
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell getprop ro.product.manufactur
er
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell df /data
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell cat /sys/devices/system/cpu/c
pu0/cpufreq/cpuinfo_max_freq
[06:43:37][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys meminfo
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys SurfaceFlinger
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell getprop ro.product.model
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys display
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys activity top
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys package com.netease.n
ie.yosemite
[06:43:43][INFO]<airtest.core.android.yosemite> local version code is 285, insta
lled version code is 285
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell settings get secure default_i
nput_method
[06:43:43][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell ime list -a
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys package com.netease.o
pen.pocoservice
installed version is 37, installer version is 37. force_reinstall=False
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys package com.netease.o
pen.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e forward --no-rebind tcp:18342 tcp:1
0080
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e forward --no-rebind tcp:12434 tcp:1
0081
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell ps
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell am force-stop com.netease.ope
n.pocoservice
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell am start -n com.netease.open.
pocoservice/.TestActivity
[06:43:44][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell am instrument -w -e debug fal
se -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.
open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
[06:43:57][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e uninstall com.netease.open.pocoserv
ice
[06:43:57][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys package com.netease.o
pen.pocoservice
installed version is None, installer version is 37. force_reinstall=False
[06:43:58][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e install e:\auto_test\poco\poco\driv
ers\android\lib\pocoservice-debug.apk
[06:43:59][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys package com.netease.o
pen.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=True
[06:43:59][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e install -r e:\auto_test\poco\poco\d
rivers\android\lib\pocoservice-debug-androidTest.apk
[06:44:01][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell am force-stop com.netease.ope
n.pocoservice
[06:44:01][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell am start -n com.netease.open.
pocoservice/.TestActivity
[06:44:01][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell am instrument -w -e debug fal
se -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.
open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
[06:44:13][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e shell dumpsys activity top
EERROR: setUpClass (__main__.CalculatorPlus)

Traceback (most recent call last):
  File "e:\auto_test\my-testflow\testflow\lib\case\android_app.py", line 24, in
setUpClass
    cls.poco = AndroidUiautomationPoco(screenshot_each_action=False)
  File "e:\auto_test\poco\poco\drivers\android\uiautomation.py", line 173, in __
init__
    raise RuntimeError("unable to launch AndroidUiautomationPoco")
RuntimeError: unable to launch AndroidUiautomationPoco

Ran 0 tests in 42.373s

FAILED (errors=1)
[06:44:13][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e forward --remove tcp:18342
[06:44:13][DEBUG]<airtest.core.android.adb> e:\auto_test\airtest\airtest\core\an
droid\static\adb\windows\adb.exe -s f089294e forward --remove tcp:12434
```
这并不是第一次执行example.py，第一次执行example会自动安装Yosemite，但是com.google.android.calculator.apk并不会安装，同时第一次执行example，也会报一样的错误。

使用Android 6.0（三星S3）设备测试，正常。可以自动启动计算器，并且测试成功。
使用Android 9.0 设备测试，也报出一样的错误。

**Comment by adolli** [comment]
请问在Android8.0和9.0上，又看到一个叫PocoService的应用装上去吗？

**Comment by wanghehacker** [comment]
@adolli 有看到PocoService，图标是一个Android的绿色机器人

**Comment by adolli** [comment]
请尝试一下最新版，如果仍然无法启动则为手机兼容性问题。先close，有问题随时reopen。

**Comment by IcyW** [comment]
遇到了+1
PC Windows 10
乐视 Le X620 6.0 1920*1080

**Comment by martin-huang** [comment]
已经是最新版本了，还是会遇到这个问题

**Comment by Germey** [comment]
See: https://github.com/AirtestProject/Poco/pull/422
