### ISSUE TITLE
list[]问题

### ISSUE THREAD

**Issue by XedGo** [AirtestProject/Poco#46]
```
2_11: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\AutoTest\wsfUIauto\TestCase\test_02_regmaster.py", line 135, in test_11_reg
    h1 = self.poco("com.wanshifu.myapplication:id/container").child("android.widget.LinearLayout")[2].child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("com.wanshifu.myapplication:id/rcv_items").child("android.widget.LinearLayout")[0].child("com.wanshifu.myapplication:id/root").child("com.wanshifu.myapplication:id/tv_content").get_text()
  File "E:\python\lib\site-packages\poco\proxy.py", line 201, in __getitem__
    return self._sorted_children[item][0]
IndexError: list index out of range
```
IDE上调试的时候没有问题，跑起来就报这个错

**Comment by XedGo** [comment]
@adolli 

```
    def test_11_reg(self):  # 家具类服务类型比对
        """注册测试用例：选择服务类型[抽取5个类型比对]"""
        self.poco("com.wanshifu.myapplication:id/rcv_items").child("com.wanshifu.myapplication:id/root")[0].child("com.wanshifu.myapplication:id/tv_content").click()
        h1 = self.poco("com.wanshifu.myapplication:id/container").child("android.widget.LinearLayout")[2].child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("com.wanshifu.myapplication:id/rcv_items").child("android.widget.LinearLayout")[0].child("com.wanshifu.myapplication:id/root").child("com.wanshifu.myapplication:id/tv_content").get_text()
        h2 = self.poco("com.wanshifu.myapplication:id/container").child("android.widget.LinearLayout")[2].child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("com.wanshifu.myapplication:id/rcv_items").child("android.widget.LinearLayout")[1].child("com.wanshifu.myapplication:id/root").child("com.wanshifu.myapplication:id/tv_content").get_text()
        h3 = self.poco("com.wanshifu.myapplication:id/container").child("android.widget.LinearLayout")[2].child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("com.wanshifu.myapplication:id/rcv_items").child("android.widget.LinearLayout")[2].child("com.wanshifu.myapplication:id/root").child("com.wanshifu.myapplication:id/tv_content").get_text()
        h4 = self.poco("com.wanshifu.myapplication:id/container").child("android.widget.LinearLayout")[2].child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("com.wanshifu.myapplication:id/rcv_items").child("android.widget.LinearLayout")[3].child("com.wanshifu.myapplication:id/root").child("com.wanshifu.myapplication:id/tv_content").get_text()
        h5 = self.poco("com.wanshifu.myapplication:id/container").child("android.widget.LinearLayout")[2].child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("com.wanshifu.myapplication:id/rcv_items").child("android.widget.LinearLayout")[3].child("com.wanshifu.myapplication:id/root").child("com.wanshifu.myapplication:id/tv_content").get_text()
        if h1 == "家具维修/检修" and h2 == "家具安装/组装" and h3 == "家具清洁保养" and h4 == "家具配送搬运" and h5 == "家具定制定做":
            success = 1
        else:
            success = 0
        self.assertEqual(success, 1)
```

**Comment by XedGo** [comment]
@adolli 解决了，是IDE的坑，使用IDE定位同一个元素时，两次给出了不同的ui path，很无语。至于为什么，不清楚

**Comment by adolli** [comment]
这种过长的定位，建议还是人工整理下，尽量不要用到下标访问，这个是不稳定的。
