### ISSUE TITLE
poco 调用wait时报错

### ISSUE THREAD

**Issue by JokinYang** [AirtestProject/Poco#481]
**描述问题bug**
调用poco.wait()时出现HTTP无法连接的错误

根据log猜测为snippet.py中_cleanup()所导致

该问题在GitHub actions所提供的容器稳定复现

相似问题：
https://github.com/AirtestProject/Airtest/issues/951

```

Traceback (most recent call last):
  File "main.py", line 329, in <module>
    momo.login_with_account(ACCOUNT, PASSWORD)
  File "main.py", line 47, in login_with_account
    self.main_page_container.wait(self.timeout)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/proxy.py", line 659, in wait
    while not self.exists():
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/proxy.py", line 774, in exists
    return self.attr('visible')
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/utils/retry.py", line 20, in wrapped
    raise ex
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/utils/retry.py", line 15, in wrapped
    return func(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/poco/utils/hrpc/hierarchy.py", line 33, in select
    return self.selector.select(query, multiple)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/hrpc/object_proxy.py", line 92, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/hrpc/client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/hrpc/transport/http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=16065): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11350e9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[13:18:00][DEBUG]<airtest.core.android.adb> /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward --remove tcp:13189
Exception ignored in: <module 'threading' from '/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/airtest/utils/snippet.py", line 89, in exitfunc
    _cleanup()
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/airtest/utils/snippet.py", line 64, in _cleanup
    func(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/airtest/core/android/adb.py", line 1566, in cleanup_adb_forward
    adb._cleanup_forwards()
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/airtest/core/android/adb.py", line 827, in _cleanup_forwards
    self.remove_forward(local)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/airtest/core/android/adb.py", line 549, in remove_forward
    self.cmd(cmds)
  File "/Users/runner/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/airtest/core/android/adb.py", line 197, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[] stderr[adb: error: listener 'tcp:13189' not found
]

[完整log地址](https://github.com/JokinYang/MomoReviewHelper/runs/3262499247?check_suite_focus=true)

```

**复现步骤**
1. clone 项目：https://github.com/JokinYang/MomoReviewHelper/
2.  项目主页 actions -> workflows -> CI -> run workflows
3. 等待workflow运行

**python 版本:** `python3.8`

**poco 版本:** `1.0.82`

**设备:**
 - 型号:  emulator in macos 
 - 系统:  api version 28
 -  GitHub actions 所提供的macos运行环境

**其他相关环境信息**
linux ubuntu 20正常运行，在macos上运行报错

**Comment by aogg** [comment]
+1
