### ISSUE TITLE
poco(text='消息').click() 报错：poco.exceptions.InvalidOperationException: Click position out of screen

### ISSUE THREAD

**Issue by journey1989** [AirtestProject/Poco#497]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 73, in runTest
    six.reraise(*sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/yixia/Documents/qwe.air/qwe.py", line 15, in <module>
    poco(text='消息').click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/pocofw.py", line 251, in click
    raise InvalidOperationException('Click position out of screen. pos={}'.format(repr(pos)))
poco.exceptions.InvalidOperationException: Click position out of screen. pos=[1.5555555555555556, 0.060648148148148145]

**复现步骤**
android 底部bar按钮，共5个

poco(text='消息').click()   点击报错
poco(text='我的').click()   点击正常切界面
poco(text='发布').click()   点击正常切界面
poco(text='发现').click()   点击正常切界面
poco(text='首页').click()   点击正常切界面

**预期效果**
点击切到消息界面

**相关截图**
无

**python 版本:** `python3.9`

**poco 版本:** `1.2.3`

**设备:**
 - 型号: vivo x20
 - 系统:Android 8.1

**其他相关环境信息**
无

**Comment by yimelia** [comment]
贴一下pip list的内容看看airtest和pocoui的版本号是多少？airtest需要更新到最新版本。
最好是能提供出我们可以复现出来的办法，比如提供测试用的apk，脚本内容等，否则我们无法复现问题

**Comment by yimelia** [comment]
https://airtestproject.s3.netease.com/downloads/temp/pocoservice-debug.apk?download=true

**Comment by journey1989** [comment]
@yimelia 更换你的包恢复正常了，感谢，什么发新版本（处理这个问题）
