### ISSUE TITLE
测试脚本成功完成，ok之后报错：ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by zeryter** [AirtestProject/Poco#52]
```python
  def find_and_scroll(cls, main_id, root_id, find_id):
        '''
        查找一个可以通过滚动找到的控件 找到后返回控件
        
        :param main_id 滚动参考元素resourceId 或者 className
        :param root_id resourceId 或者 className, 用于根元素设定
        :param find_id resourceId 或者 className，需要查找的元素
        :return: 返回poco对象 或者None
        '''

        temp = []
        flag = 3
        while True:
            id_temps = []

            for i in poco(main_id).children():
                id_temps.append(i.get_name())

                # 开始查找元素
                if poco(root_id).exists():
                    for p in poco(root_id).offspring():
                        print(p.get_name(), end="\n\n-----\n")

                        if p.get_name() == find_id:
                            print("这里返回了P")
                            return p
                else:
                    for p in poco(main_id).offspring():
                        if p.get_name() == find_id:
                            print("这里返回了P eles")
                            return p

            # 滚动 处理
            poco.scroll(percent=0.3, duration=0.2)

            if temp == id_temps:
                flag -= 1
                print('还有{}次机会'.format(flag))
                if not flag:
                    return
            else:
                flag = 3

            temp = id_temps
```
整个脚本只执行这一个方法

脚本日志
```
...
...
...
--------------------------------------------------------------
Ran 1 test in 41.414s


OK
[10:01:18][DEBUG]<airtest.core.android.adb> /Users/xxx/venv/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -s HKR4C15811018547 forward --remove tcp:17810
[10:01:18][DEBUG]<airtest.core.android.adb> /Users/xxx/venv/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -s HKR4C15811018547 forward --remove tcp:19793
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of com.netease.open.libpoco.Node@19aff031>'>
Traceback (most recent call last):
  File "/Users/xxx/venv/lib/python3.6/site-packages/hrpc/object_proxy.py", line 110, in __del__
  File "/Users/xxx/venv/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
  File "/Users/xxx/venv/lib/python3.6/site-packages/hrpc/transport/http.py", line 19, in send
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/api.py", line 112, in post
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/api.py", line 58, in request
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/sessions.py", line 499, in request
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/sessions.py", line 672, in merge_environment_settings
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/utils.py", line 692, in get_environ_proxies
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/utils.py", line 676, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2612, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2536, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@188d2db5>'>
Traceback (most recent call last):
  File "/Users/xxx/venv/lib/python3.6/site-packages/hrpc/object_proxy.py", line 110, in __del__
  File "/Users/xxx/venv/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
  File "/Users/xxx/venv/lib/python3.6/site-packages/hrpc/transport/http.py", line 19, in send
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/api.py", line 112, in post
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/api.py", line 58, in request
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/sessions.py", line 499, in request
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/sessions.py", line 672, in merge_environment_settings
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/utils.py", line 692, in get_environ_proxies
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/utils.py", line 676, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2612, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2536, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down
`
```

**Comment by adolli** [comment]
请问你是用的AirtestIDE版本号是？

**Comment by zeryter** [comment]
最新的 v0.1.5

**Comment by zeryter** [comment]
不好意思  代码没写全  现在更新了

**Comment by adolli** [comment]
这个报错是因为python运行完退出了导致了，是不是你脚本已经运行完了？

**Comment by zeryter** [comment]
对  已经运行完了  日志显示OK  然后报错

**Comment by zeryter** [comment]
不知道是什么把Python给关闭了  整个脚本只执行这一个方法  神奇的bug   辛苦你们了

**Comment by adolli** [comment]
我看你在代码里调用了`poco().children()`和`poco().offspring()`的循环遍历，中途会创建出大量的UIProxy临时对象，这很容易导致远程对象释放异常，可以尝试下下面的写法。 [about frozen poco](https://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/poco-example/optimize_speed_by_freezing_UI.html)
```python
frozen_poco = poco.freeze()
for child in frozen_poco('xxx').children():
    pass
```

**Comment by zeryter** [comment]
好的  谢谢  之前是在找滚动查找的解决方案  各种尝试后  这个方案还行  还没有进行优化  谢谢你的建议
