### ISSUE TITLE
运行压测case，时间久了会失去连接

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#53]
目前本地排查usb线连接正常，手机也是刚买不久
[log.txt](https://github.com/AirtestProject/Poco/files/2227055/log.txt)

**Comment by lycfr** [comment]
pocoui==1.0.66
运行大概40几分钟吧，不过后面又出现了，运行了3分钟左右也报错

======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/meitu/sharePic.air/sharePic.py", line 37, in <module>
    if not poco("com.mt.mtxx.mtxx:id/rv_schedules").exists():
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 659, in exists
    return self.attr('visible')
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/usr/local/lib/python3.4/dist-packages/poco/utils/hrpc/hierarchy.py", line 27, in select
    return self.selector.select(query, multiple)
  File "/usr/local/lib/python3.4/dist-packages/hrpc/object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "/usr/local/lib/python3.4/dist-packages/hrpc/client.py", line 78, in evaluate
    raise RpcRemoteException(resp)
hrpc.exceptions.RpcRemoteException: java.lang.IllegalStateException: UiAutomation not connected!

|--   Remote Traceback   --|

java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:414)
	at com.netease.open.pocoservice.Dumper.getRoot(Dumper.java:30)
	at com.netease.open.pocoservice.Dumper.getRoot(Dumper.java:17)
	at com.netease.open.libpoco.sdk.Selector.getRoot(Selector.java:135)
	at com.netease.open.libpoco.sdk.Selector.select(Selector.java:37)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:170)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:818)


|--   Remote Traceback end   --|

**Comment by lycfr** [comment]
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 536, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/meitu/sharePic.air/sharePic.py", line 37, in <module>
    if not poco("com.mt.mtxx.mtxx:id/rv_schedules").exists():
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 659, in exists
    return self.attr('visible')
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/usr/local/lib/python3.4/dist-packages/poco/utils/hrpc/hierarchy.py", line 27, in select
    return self.selector.select(query, multiple)
  File "/usr/local/lib/python3.4/dist-packages/hrpc/object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "/usr/local/lib/python3.4/dist-packages/hrpc/client.py", line 64, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/usr/local/lib/python3.4/dist-packages/hrpc/transport/http.py", line 19, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

----------------------------------------------------------------------
Ran 1 test in 1864.798s

FAILED (errors=1)
[11:34:32][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:15143
[11:34:32][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:12315
[11:34:32][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:13995
[11:34:32][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:15962
[11:34:32][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended

**Comment by lycfr** [comment]
发现这个应该是必现的，我每次运行大概40分钟左右，然后就失去连接了，服务没起来

**Comment by adolli** [comment]
基本上已经定位问题，目前正在尝试修复这个。

**Comment by adolli** [comment]
fixed at `pocoui==1.0.67`. try to upgrade by `pip install -U pocoui`.

**Comment by adolli** [comment]
https://github.com/AirtestProject/Poco/issues/57
