### ISSUE TITLE
如果不优先启动加入poco-sdk的游戏，poco初始化时RPC报异常，如果游戏启动后，poco可正常初始化

### ISSUE THREAD

**Issue by yusandy0920** [AirtestProject/Poco#531]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
poco初始化时RPC报异常

**描述问题bug**
如果不优先启动加入poco-sdk的游戏，poco初始化时RPC报异常

```
（在这里粘贴traceback或其他报错信息）
[16:53:05][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[16:53:06][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "airtest\cli\runner.py", line 70, in runTest
  File "D:\dev\workspace\MyAirtest.air\MyAirtest.py", line 13, in <module>
    pocoService = CocosJsPoco(device=device)
  File "D:\SW\AirtestIDE\poco\drivers\cocosjs\__init__.py", line 97, in __init__
    agent = CocosJsPocoAgent(port, device)
  File "D:\SW\AirtestIDE\poco\drivers\cocosjs\__init__.py", line 52, in __init__
    self.c.connect()
  File "D:\SW\AirtestIDE\poco\utils\simplerpc\rpcclient.py", line 23, in connect
    self._wait_connected(timeout)
  File "D:\SW\AirtestIDE\poco\utils\simplerpc\rpcclient.py", line 40, in _wait_connected
    raise RpcConnectionError("Rpc Connection Closed")
poco.utils.simplerpc.simplerpc.RpcConnectionError: Rpc Connection Closed

======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 73, in runTest
  File "site-packages\six.py", line 703, in reraise
  File "airtest\cli\runner.py", line 70, in runTest
  File "D:\dev\workspace\MyAirtest.air\MyAirtest.py", line 13, in <module>
    pocoService = CocosJsPoco(device=device)
  File "D:\SW\AirtestIDE\poco\drivers\cocosjs\__init__.py", line 97, in __init__
    agent = CocosJsPocoAgent(port, device)
  File "D:\SW\AirtestIDE\poco\drivers\cocosjs\__init__.py", line 52, in __init__
    self.c.connect()
  File "D:\SW\AirtestIDE\poco\utils\simplerpc\rpcclient.py", line 23, in connect
    self._wait_connected(timeout)
  File "D:\SW\AirtestIDE\poco\utils\simplerpc\rpcclient.py", line 40, in _wait_connected
    raise RpcConnectionError("Rpc Connection Closed")
poco.utils.simplerpc.simplerpc.RpcConnectionError: Rpc Connection Closed

----------------------------------------------------------------------
Ran 1 test in 4.306s

FAILED (errors=1)
[16:53:06][DEBUG]<airtest.core.android.adb> D:\SW\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s AF8Y6R1809003994 forward --remove tcp:15043
[16:53:06][DEBUG]<airtest.core.android.adb> D:\SW\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s AF8Y6R1809003994 forward --remove tcp:15526
[16:53:06][DEBUG]<airtest.utils.nbsp> [rotation_server]b''
[16:53:06][DEBUG]<airtest.utils.nbsp> [minicap_server]b''
[Finished]

============================================================

**复现步骤**
1.游戏A不启动
2. 初始化代码如下：
    device = connect_device("Android:///" + sn)
    poco = CocosJsPoco(device=device)
**预期效果**
正常初始化poco

**相关截图**
无

**python 版本:** `python3.8`

**poco 版本:** `1.0.85`

**设备:**
 - 型号: [Honor Play5T Pro]
 - 系统: [Android 10]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
是的，就是这样的设定，必须要先启动游戏，否则连不上服务。
