### ISSUE TITLE
pocoservice.apk 不断重启问题，已开耗电模式

### ISSUE THREAD

**Issue by ygx9960** [AirtestProject/Poco#542]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
使用纯python的pocoui==1.0.87运行，pocoservice不断重启，airtestide没有这个问题

```
（在这里粘贴traceback或其他报错信息）
adb server version (40) doesn't match this client (41); killing...
[17:35:24][DEBUG]<airtest.utils.nbsp> [airtouch_server]b''
[17:35:24][DEBUG]<airtest.utils.nbsp> [rotation_server]b''
[17:35:24][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
* daemon started successfully
adb devices 输出的内容是: List of devices attached
10HC330LBQ000LM	device


[17:35:24][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
[17:35:24][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/adb.py", line 374, in shell
    out = self.raw_shell(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/adb.py", line 332, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/adb.py", line 197, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b''] stderr[b"adb server version (41) doesn't match this client (40); killing...\nADB server didn't ACK\nFull server startup log: /var/folders/7c/fszzby153bv26qy7qnmq7vvw0000gn/T//adb.501.log\nServer had pid: 97030\n--- adb starting (pid 97030) ---\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] Android Debug Bridge version 1.0.40\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] Version 4986621\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] Installed as /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] \nadb I 05-06 17:35:25 97030 1943186 usb_osx.cpp:308] reported max packet size for 10HC330LBQ000LM is 512\nerror: could not install *smartsocket* listener: Address already in use\n\n* failed to start daemon\nerror: cannot connect to daemon\n"]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/adb.py", line 376, in shell
    raise AdbShellError(err.stdout, err.stderr)
airtest.core.error.AdbShellError: stdout[b''] stderr[b"adb server version (41) doesn't match this client (40); killing...\nADB server didn't ACK\nFull server startup log: /var/folders/7c/fszzby153bv26qy7qnmq7vvw0000gn/T//adb.501.log\nServer had pid: 97030\n--- adb starting (pid 97030) ---\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] Android Debug Bridge version 1.0.40\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] Version 4986621\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] Installed as /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb\nadb I 05-06 17:35:25 97030 1943181 main.cpp:56] \nadb I 05-06 17:35:25 97030 1943186 usb_osx.cpp:308] reported max packet size for 10HC330LBQ000LM is 512\nerror: could not install *smartsocket* listener: Address already in use\n\n* failed to start daemon\nerror: cannot connect to daemon\n"]
python-BaseException
[17:35:28][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice/androidx.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
[17:35:31][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:32][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:33][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:34][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:35][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:36][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:37][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:39][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:40][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
[17:35:41][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
[17:35:46][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am start -n com.netease.open.pocoservice/.TestActivity
[17:35:46][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 10HC330LBQ000LM shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice/androidx.test.runner.AndroidJUnitRunner

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

```

**复现步骤**
1. 打开微信
2. 到微信聊天框
3. pocoservice开始不断重启，然后微信闪退，wifi网络异常，wifi关闭重新打开网络才能恢复

**预期效果**
不重启正常执行

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.8`

**poco 版本:** `pocoui==1.0.87`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. vivo Y10]
 - 系统: [e.g. Android 11]
 - vivo系统：[e.g. oriainos]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by cscli** [comment]
...
