### ISSUE TITLE
Linux下执行运行脚本，安装完minitouch后脚本就卡住不会运行

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#55]
![image](https://user-images.githubusercontent.com/29672247/43316387-cc0bba3a-91cb-11e8-8a50-81e4967fa9f1.png)

**Comment by lycfr** [comment]
s/arm64-v8a/minitouch /data/local/tmp/minitouch
[06:32:00][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 shell chmod 755 /data/local/tmp/minitouch
[06:32:00][INFO]<airtest.core.android.minitouch> install_minitouch finished
[06:32:00][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[06:32:00][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --no-rebind tcp:15078 localabstract:minitouch_15078
[06:32:00][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 shell /data/local/tmp/minitouch -n 'minitouch_15078' 2>&1
[06:32:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/event12 was outscored by /dev/input/event11 (22449 >= 21440)'
[06:32:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type B touch device synaptics_dsx_i2c (1080x1920 with 10 contacts) detected on /dev/input/event11 (score 22449)'
^C[06:36:43][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/airtest/__main__.py", line 6, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/__main__.py", line 16, in main
    run_script(args)
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 141, in run_script
    result = unittest.TextTestRunner(verbosity=0).run(suite)
  File "/usr/lib/python3.4/unittest/runner.py", line 168, in run
    test(result)
  File "/usr/lib/python3.4/unittest/suite.py", line 87, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.4/unittest/suite.py", line 125, in run
    test(result)
  File "/usr/lib/python3.4/unittest/case.py", line 622, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.4/unittest/case.py", line 574, in run
    testMethod()
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/meitu/sharePic.air/sharePic.py", line 30, in <module>
    touch(Template(r"tpl1532484729901.png", record_pos=(0.319, 0.64), resolution=(1080, 1920)))
  File "/usr/local/lib/python3.4/dist-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/api.py", line 261, in touch
    G.DEVICE.touch(pos, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/android/android.py", line 320, in touch
    self.minitouch.touch(pos, duration=duration)
  File "/usr/local/lib/python3.4/dist-packages/airtest/utils/snippet.py", line 104, in ready_func
    method()
  File "/usr/local/lib/python3.4/dist-packages/airtest/utils/snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/android/minitouch.py", line 55, in install_and_setup
    self.setup_client()
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/android/minitouch.py", line 502, in setup_client
    header += s.sock.recv(4096)  # size is not strict, so use raw socket.recv
KeyboardInterrupt
[06:36:43][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:13013
[06:36:43][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:18678
[06:36:43][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:12697
[06:36:43][DEBUG]<airtest.core.android.adb> /home/meitu/Software/android/platform-tools/adb -s K50GLD2681200191 forward --remove tcp:15078

**Comment by lycfr** [comment]
airtest==1.0.21
美图M6 6.0系统
脚本报错在第29行

**Comment by adolli** [comment]
这个手机在AirtestIDE中可以正常使用不？另外还有你是用的linux版本和python版本是？我们在linux下测试过大部分发行版都是ok的

**Comment by lycfr** [comment]
在airtestIDE是正常，也不是必现，只是有时候没跑过，拿来跑一下就会出现这个问题
Linux版本：3.19.0-25
Python版本：3.4

**Comment by adolli** [comment]
同一个linux主机换一个手机是否ok呢？

**Comment by lycfr** [comment]
手机有换过其他品牌的手机以及电脑也换过，都会存在这个问题。

**Comment by adolli** [comment]
那你可能需要自己调试下linux上的环境了，检查kernel的tcp与socket相关配置是否异常。

**Comment by Meteorix** [comment]
新版的airtest和IDE应该已经修复了这个问题，如果还有问题再开issue吧
