### ISSUE TITLE
长时间运行pocoservice.apk不断重启

### ISSUE THREAD

**Issue by testdafei** [AirtestProject/Poco#567]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
pocoservice.apk不断重启，导致手机发热严重，手机卡顿，用例无法顺利执行。插拔一次USB数据线可以恢复正常

```
（在这里粘贴traceback或其他报错信息）
报错信息
pocoAirTest/testcase/005/test_bookfriends_rank/test_bookfriends_rank_page.py::TestBookfriendsRankPage::test_change_ranking_tab[newPoco0-current_state_Poco0] Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@6bb86c4>'>
Traceback (most recent call last):
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
    timeout=None if wait_for_response else 0.3)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/transport/http.py", line 24, in send
    timeout=timeout)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=12785): Read timed out. (read timeout=0.3)
++++ UIObjectProxy of "text=同意"
++++ UIObjectProxy of "com.kmxs.reader:id/view_gender_choose_girl"
++++ UIObjectProxy of "text=我的"
++++ UIObjectProxy of "text=我的"
++++ UIObjectProxy of "text=点击登录"
(878, 173)
(1080, 2340)
0.81 0.07
++++ UIObjectProxy of "com.kmxs.reader:id/tv_load_more_title"
++++ UIObjectProxy of "com.kmxs.reader:id/interact_layout"
++++ UIObjectProxy of "text=总榜&android.widget.TextView"
++++ UIObjectProxy of "text=月榜&android.widget.TextView"
PASSED
pocoAirTest/testcase/005/test_help_and_feedback/test_help_feedback.py::TestHelpAndFeedback::test_goto_my_feedback[newPoco0-current_state_Poco0] ++++ UIObjectProxy of "text=同意"
++++ UIObjectProxy of "com.kmxs.reader:id/view_gender_choose_girl"
++++ UIObjectProxy of "text=我的"
++++ UIObjectProxy of "text=我的"
++++ UIObjectProxy of "text=点击登录"
(878, 173)
(1080, 2340)
0.81 0.07
未找到帮助反馈入口！
RERUN
pocoAirTest/testcase/005/test_help_and_feedback/test_help_feedback.py::TestHelpAndFeedback::test_goto_my_feedback[newPoco0-current_state_Poco0] (878, 173)
(1080, 2340)
0.81 0.07
++++ UIObjectProxy of "text=帮助与反馈"
++++ UIObjectProxy of "com.kmxs.reader:id/tb_right_text"
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of com.netease.open.libpoco.Node@b5e9a82>'>
Traceback (most recent call last):
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
    timeout=None if wait_for_response else 0.3)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/transport/http.py", line 24, in send
    timeout=timeout)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19537): Read timed out. (read timeout=0.3)
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of com.netease.open.libpoco.Node@8f7e195>'>
Traceback (most recent call last):
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
    timeout=None if wait_for_response else 0.3)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/transport/http.py", line 24, in send
    timeout=timeout)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19537): Read timed out. (read timeout=0.3)
PASSED
pocoAirTest/testcase/005/test_help_and_feedback/test_help_feedback.py::TestHelpAndFeedback::test_feedback[newPoco0-current_state_Poco0] ++++ UIObjectProxy of "com.kmxs.reader:id/rl_feedback_edit"
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@d5b0d91>'>
Traceback (most recent call last):
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
    timeout=None if wait_for_response else 0.3)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/transport/http.py", line 24, in send
    timeout=timeout)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19537): Read timed out. (read timeout=0.3)
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@c667f20>'>
Traceback (most recent call last):
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
    timeout=None if wait_for_response else 0.3)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/transport/http.py", line 24, in send
    timeout=timeout)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19537): Read timed out. (read timeout=0.3)
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of com.netease.open.libpoco.Node@5a7b985>'>
Traceback (most recent call last):
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/client.py", line 64, in evaluate
    timeout=None if wait_for_response else 0.3)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/hrpc/transport/http.py", line 24, in send
    timeout=timeout)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/PycharmProject/qaarm-uiautotest/py3.6env/lib/python3.6/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=18530): Read timed out. (read timeout=0.3)
still waiting for uiautomation ready.


**复现步骤**
1. 长时间运行半小时以上

**预期效果**
(预期想要得到什么、见到什么)
正常长时间运行
**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.8`

**poco 版本:** pocoui==1.0.87  airtest==1.2.6

> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - HUAWEI  spn-al00
 - 系统: [e.g. Android 8.1]
 - harmonyos2.0.0
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)
macos

**Comment by willie-li** [comment]
同问

**Comment by cscli** [comment]
pip list | grep poco
poco 0.99.1
pocoui 1.0.88
pip list | grep airtest
airtest 1.2.10.2
pocoservice 自启动打开，电池优化关闭，我的问题就没再出现

**Comment by cscli** [comment]
> Referen
pocoservice的版本可以特别注意下， 我的1.0.0.45 1.0.0.50都是正常，1.0.0.61有问题
