### ISSUE TITLE
vivo手机 安卓13 click后报错 执行下一条 click时一直卡住，急，求解决方法

### ISSUE THREAD

**Issue by vivouser01** [AirtestProject/Poco#568]
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_13098'
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'java.lang.NoSuchMethodException: android.view.SurfaceControl.screenshot [class android.graphics.Rect, int, int, int]'
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at java.lang.Class.getMethod(Class.java:2103)'
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at java.lang.Class.getDeclaredMethod(Class.java:2081)'
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at com.netease.nie.yosemite.compat.ScreenshotManagerWrapper$NewApiScreenshotInjector.injectorMethod(ScreenshotManagerWrapper.java:123)'
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at com.netease.nie.yosemite.compat.ScreenshotManagerWrapper.<init>(ScreenshotManagerWrapper.java:28)'
[17:51:37][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at com.netease.nie.yosemite.Capture$InputClient.run(Capture.java:168)'
[17:51:38][ERROR]<airtest.core.android.cap_methods.screen_proxy> OSError('socket connection broken',)
[17:51:38][ERROR]<airtest.core.android.cap_methods.screen_proxy> Javacap setup up failed!
D:\Users\11138551\Desktop\AirtestIDE\airtest\core\android\cap_methods\adbcap.py:10: UserWarning: Currently using ADB screenshots, the efficiency may be very low.
  warnings.warn("Currently using ADB screenshots, the efficiency may be very low.")
[17:51:38][DEBUG]<airtest.core.android.adb> D:\Users\11138551\Desktop\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 400D1K002100000 shell screencap -p
[17:51:38][DEBUG]<airtest.utils.nbsp> [javacap_sever]b''
[17:51:38][DEBUG]<airtest.core.android.adb> D:\Users\11138551\Desktop\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 400D1K002100000 shell screencap -p
[17:51:39][DEBUG]<airtest.core.android.adb> D:\Users\11138551\Desktop\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 400D1K002100000 shell ls -l /data/local/tmp/maxpresent.jar
[17:51:39][DEBUG]<airtest.core.android.touch_methods.maxtouch> install_maxtouch skipped
[17:51:39][DEBUG]<airtest.core.android.adb> D:\Users\11138551\Desktop\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 400D1K002100000 forward --no-rebind tcp:16782 localabstract:maxpresent_16782
[17:51:39][DEBUG]<airtest.core.android.adb> D:\Users\11138551\Desktop\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 400D1K002100000 shell app_process -Djava.class.path=/data/local/tmp/maxpresent.jar /data/local/tmp com.netease.maxpresent.MaxPresent socket maxpresent_16782
[17:51:39][DEBUG]<airtest.utils.nbsp> [airtouch_server]b'Metrics Message : 2800.0=====1968.0'
[17:51:39][DEBUG]<airtest.utils.nbsp> [airtouch_server]b'Start local socket (maxpresent_16782) server...'
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@ce4b081>'>
Traceback (most recent call last):
  File "hrpc\object_proxy.py", line 114, in __del__
  File "hrpc\client.py", line 64, in evaluate
  File "hrpc\transport\http.py", line 24, in send
  File "site-packages\requests\api.py", line 119, in post
  File "site-packages\requests\api.py", line 61, in request
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 529, in send
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19831): Read timed out. (read timeout=0.3)

**Comment by vivouser01** [comment]
![mm_facetoface_collect_qrcode_1666487270077](https://user-images.githubusercontent.com/124675562/217219212-24ec09d6-33ee-493c-9852-dff7f229f00b.png)

**Comment by vivouser01** [comment]
![abfb13ea-d09a-4cb7-a4f6-a948d5c2539b](https://user-images.githubusercontent.com/124675562/217219600-e2c543ea-f691-4fe0-bd1d-e8da86154a64.jpg)
