### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#57]
[08:05:18][DEBUG]<airtest.aircv.template> threshold=0.7, result={'rectangle': ((852, 891), (852, 978), (1043, 978), (1043, 891)), 'confidence': 0.9959992170333862, 'result': (947, 934)}
[08:05:18][DEBUG]<airtest.core.api> match result: {'rectangle': ((852, 891), (852, 978), (1043, 978), (1043, 891)), 'confidence': 0.9959992170333862, 'result': (947, 934)}
[08:05:18][INFO]<airtest.core.api> Try finding:
Template(/home/meitu/sharePic.air/tpl1532484856526.png)
[08:05:18][DEBUG]<airtest.core.api> try match with _find_template
[08:05:18][DEBUG]<airtest.aircv.template> threshold=0.7, result={'rectangle': ((852, 891), (852, 978), (1039, 978), (1039, 891)), 'confidence': 0.9956527352333069, 'result': (945, 934)}
[08:05:18][DEBUG]<airtest.core.api> match result: {'rectangle': ((852, 891), (852, 978), (1039, 978), (1039, 891)), 'confidence': 0.9956527352333069, 'result': (945, 934)}
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@566643f>'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hrpc/object_proxy.py", line 110, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/usr/local/lib/python3.4/dist-packages/hrpc/client.py", line 64, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/usr/local/lib/python3.4/dist-packages/hrpc/transport/http.py", line 19, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/meitu/sharePic.air/sharePic.py", line 15, in <module>
    if poco("com.mt.mtxx.mtxx:id/lottie_camera").exists():
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 659, in exists
    return self.attr('visible')
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "/usr/local/lib/python3.4/dist-packages/poco/proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/usr/local/lib/python3.4/dist-packages/poco/utils/hrpc/hierarchy.py", line 27, in select
    return self.selector.select(query, multiple)
  File "/usr/local/lib/python3.4/dist-packages/hrpc/object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "/usr/local/lib/python3.4/dist-packages/hrpc/client.py", line 64, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/usr/local/lib/python3.4/dist-packages/hrpc/transport/http.py", line 19, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

----------------------------------------------------------------------
Ran 1 test in 107.294s

FAILED (errors=1)
[08:05:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:11682
[08:05:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:14756
[08:05:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:19167
[08:05:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:16399
[08:05:32][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended

**Comment by lycfr** [comment]
[log.txt](https://github.com/AirtestProject/Poco/files/2241087/log.txt)
附上log附件

**Comment by adolli** [comment]
fixed at `pocoui==1.0.67`. try to upgrade by `pip install -U pocoui`.
