### ISSUE TITLE
pocoservice.apk在使用过程中出现重启

### ISSUE THREAD

**Issue by 1152606951** [AirtestProject/Poco#594]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
1.在连接手机进行测试时,跑了四五个用例后,pocoservice.apk开始频繁重启并和测试app切屏

```
log信息截图
（在这里粘贴traceback或其他报错信息）
![image](https://github.com/AirtestProject/Poco/assets/69802592/f7df5468-1fb6-408d-a704-c9a6f7bc8376)

```

**复现步骤**
1.执行用例
2.pocoservicer重启

**预期效果**
正常不重启pocoservice程序
**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

https://github.com/AirtestProject/Poco/assets/69802592/224f0741-34df-4a1e-b92f-40c4873e5274

**python 版本:** `python3.11.3`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [小米13]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by joyerf** [comment]
2024-10-16 16:04:03.914 20159-20190 AndroidRuntime          com.netease.open.pocoservice         E  FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
                                                                                                    Process: com.netease.open.pocoservice, PID: 20159
                                                                                                    java.lang.IllegalStateException: Cannot call disconnect() while connecting UiAutomation@e519f59[id=-1, flags=0]
                                                                                                    	at android.app.UiAutomation.disconnect(UiAutomation.java:377)
                                                                                                    	at android.app.Instrumentation.finish(Instrumentation.java:281)
                                                                                                    	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:422)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:457)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2269)
