### ISSUE TITLE
当无障碍服务出现故障无法被使用时，poco就会一直重启，这两者是否存在关系

### ISSUE THREAD

**Issue by aogg** [AirtestProject/Poco#619]
如题

**Comment by aogg** [comment]
那些自启动啥啥的都已经配置过了，而且本来是好好的

**Comment by joyerf** [comment]
2024-10-16 16:04:03.914 20159-20190 AndroidRuntime          com.netease.open.pocoservice         E  FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
                                                                                                    Process: com.netease.open.pocoservice, PID: 20159
                                                                                                    java.lang.IllegalStateException: Cannot call disconnect() while connecting UiAutomation@e519f59[id=-1, flags=0]
                                                                                                    	at android.app.UiAutomation.disconnect(UiAutomation.java:377)
                                                                                                    	at android.app.Instrumentation.finish(Instrumentation.java:281)
                                                                                                    	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:422)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:457)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2269)
