### ISSUE TITLE
脚本压测过程，socket connection broken

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#62]
Template(/home/meitu/sharePic.air/tpl1532484671646.png)
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/meitu/sharePic.air/sharePic.py", line 27, in <module>
    if exists(Template(r"tpl1532484671646.png", record_pos=(0.316, 0.637), resolution=(1080, 1920))):
  File "/usr/local/lib/python3.4/dist-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/api.py", line 410, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/usr/local/lib/python3.4/dist-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/android/android.py", line 206, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/android/minicap.py", line 313, in get_frame_from_stream
    return six.next(self.frame_gen)
  File "/usr/local/lib/python3.4/dist-packages/airtest/core/android/minicap.py", line 246, in _get_stream
    header = s.recv(4)
  File "/usr/local/lib/python3.4/dist-packages/airtest/utils/safesocket.py", line 32, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken

----------------------------------------------------------------------
Ran 1 test in 1910.567s

FAILED (errors=1)
[11:30:59][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:14795
[11:30:59][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:14200
[11:30:59][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:14126
[11:30:59][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 forward --remove tcp:14665
[11:30:59][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[11:30:59][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.4/dist-packages/airtest/core/android/static/adb/linux/adb -s MAYGLD26C2300377 shell am force-stop com.netease.open.pocoservice
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@f51ec4e>'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hrpc/object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "/usr/local/lib/python3.4/dist-packages/hrpc/client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/usr/local/lib/python3.4/dist-packages/hrpc/transport/http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=14200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf03e1fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by adolli** [comment]
没看出来你这个调用了什么操作。但是发生了两件事
* pocoservice退出了（原因不明）
  > [pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
  > [pocoservice.apk] stderr: b''
  > [pocoservice.apk] retrying instrumentation PocoService
* minicap挂了，设备兼容性问题或进程被杀
