### ISSUE TITLE
PocoService一直不断重启

### ISSUE THREAD

**Issue by joyerf** [AirtestProject/Poco#621]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**PocoService不停重启**
使用 Airtest IDE 1.2.17 在连接真机，点击 Poco 辅助窗UI渲染数之后，手机上不断提示 poco service is running

```
2024-10-16 16:24:38.538 25035-25035 nativeloader            com.netease.open.pocoservice         D  Load libpowerhalwrap_jni.so using system ns (caller=/system/framework/mediatek-framework.jar): ok
2024-10-16 16:24:38.540 25035-25035 PowerHalWrapper         com.netease.open.pocoservice         I  PowerHalWrapper.getInstance 
2024-10-16 16:24:38.555 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@6f7aae0 in: PAUSED
2024-10-16 16:24:38.560 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@6f7aae0 in: STOPPED
2024-10-16 16:24:40.377 25035-25041 pen.pocoservic          com.netease.open.pocoservice         I  Compiler allocated 4542KB to compile void android.view.ViewRootImpl.performTraversals()
2024-10-16 16:26:22.938 25035-25277 System.out              com.netease.open.pocoservice         I  {"id":"6a685ff1-4da4-4b98-b00e-b6b6d0d8effb","uri":"poco-uiautomation-framework","method":[["getattr","dumper"],["getattr","dumpHierarchy"],["call",[]]],"session_id":"0d725882-fbe0-4ec0-b3a9-bdf3babb2e03"}
2024-10-16 16:26:34.260 25035-25292 System.out              com.netease.open.pocoservice         I  {"id":"c03b316a-ec59-4c45-a623-03bd1fb8418e","uri":"poco-uiautomation-framework","method":[["getattr","dumper"],["getattr","dumpHierarchy"],["call",[]]],"session_id":"0d725882-fbe0-4ec0-b3a9-bdf3babb2e03"}
2024-10-16 16:26:34.320 25035-25297 libMEOW                 com.netease.open.pocoservice         D  meow new tls: 0xb40000777fe4b500
2024-10-16 16:26:34.321 25035-25297 libMEOW                 com.netease.open.pocoservice         D  applied 1 plugins for [com.netease.open.pocoservice]:
2024-10-16 16:26:34.321 25035-25297 libMEOW                 com.netease.open.pocoservice         D    plugin 1: [libMEOW_gift.so]: 0xb400007774a9fd40
2024-10-16 16:26:34.321 25035-25297 libMEOW                 com.netease.open.pocoservice         D  rebuild call chain: 0xb40000777fe5ac40
2024-10-16 16:26:34.322 25035-25297 libMEOW                 com.netease.open.pocoservice         D  meow delete tls: 0xb40000777fe4b500
2024-10-16 16:26:34.335 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@d39f28a in: PRE_ON_CREATE
2024-10-16 16:26:34.367 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@d39f28a in: CREATED
2024-10-16 16:26:34.369 25035-25035 Quality                 com.netease.open.pocoservice         I  ActivityThread: activityStart delay 54 com.netease.open.pocoservice 25035
2024-10-16 16:26:34.371 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@d39f28a in: STARTED
2024-10-16 16:26:34.373 25035-25035 PocoService             com.netease.open.pocoservice         I  onResume
2024-10-16 16:26:34.417 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@d39f28a in: RESUMED
2024-10-16 16:26:34.430 25035-25035 WindowManager           com.netease.open.pocoservice         D  Add to mViews: DecorView@6d68cf4[TestActivity],pkg= com.netease.open.pocoservice
2024-10-16 16:26:34.437 25035-25035 ViewRootIm...tActivity] com.netease.open.pocoservice         D  hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
2024-10-16 16:26:34.458 25035-25035 Quality                 com.netease.open.pocoservice         I  ActivityThread: activityResume delay 84 com.netease.open.pocoservice 25035
2024-10-16 16:26:34.462 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@6f7aae0 in: RESTARTED
2024-10-16 16:26:34.464 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@6f7aae0 in: STARTED
2024-10-16 16:26:34.472 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@d39f28a in: PAUSED
2024-10-16 16:26:34.475 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@6f7aae0 in: STOPPED
2024-10-16 16:26:34.481 25035-25035 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@d39f28a in: STOPPED
2024-10-16 16:26:34.643 25035-25042 pen.pocoservic          com.netease.open.pocoservice         I  Background concurrent copying GC freed 2214KB AllocSpace bytes, 34(1328KB) LOS objects, 66% free, 3932KB/11MB, paused 1.147ms,51us total 132.665ms
2024-10-16 16:26:35.582 25035-25306 System.out              com.netease.open.pocoservice         I  {"id":"a7d7037f-078f-43bb-91aa-87b01d2c1d3f","uri":"poco-uiautomation-framework","method":[["getattr","dumper"],["getattr","dumpHierarchy"],["call",[]]],"session_id":"0d725882-fbe0-4ec0-b3a9-bdf3babb2e03"}
2024-10-16 16:26:36.759 25035-25315 System.out              com.netease.open.pocoservice         I  {"id":"560fddfd-c313-44d8-84d4-f44b8169a594","uri":"poco-uiautomation-framework","method":[["getattr","dumper"],["getattr","dumpHierarchy"],["call",[]]],"session_id":"0d725882-fbe0-4ec0-b3a9-bdf3babb2e03"}
2024-10-16 16:26:38.577 25325-25325 nativeloader            com.netease.open.pocoservice         D  Configuring clns-4 for other apk /data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.netease.open.pocoservice
2024-10-16 16:26:38.580 25325-25325 Quality                 com.netease.open.pocoservice         I  ActivityThread: createClassLoader delay 453 /data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/base.apk 25325
2024-10-16 16:26:38.585 25325-25325 Quality                 com.netease.open.pocoservice         I  ActivityThread: createOrUpdateClassLoaderLocked delay 461 com.netease.open.pocoservice 25325
2024-10-16 16:26:38.609 25325-25325 GraphicsEnvironment     com.netease.open.pocoservice         V  ANGLE Developer option for 'com.netease.open.pocoservice' set to: 'default'
2024-10-16 16:26:38.610 25325-25325 GraphicsEnvironment     com.netease.open.pocoservice         V  Neither updatable production driver nor prerelease driver is supported.
2024-10-16 16:26:38.637 25325-25325 NetworkSecurityConfig   com.netease.open.pocoservice         D  No Network Security Config specified, using platform default
2024-10-16 16:26:38.639 25325-25325 NetworkSecurityConfig   com.netease.open.pocoservice         D  No Network Security Config specified, using platform default
2024-10-16 16:26:38.640 25325-25325 MonitoringInstr         com.netease.open.pocoservice         I  newApplication called!
2024-10-16 16:26:38.644 25325-25325 MultiDex                com.netease.open.pocoservice         I  VM with version 2.1.0 has multidex support
2024-10-16 16:26:38.644 25325-25325 MultiDex                com.netease.open.pocoservice         I  Installing application
2024-10-16 16:26:38.644 25325-25325 MultiDex                com.netease.open.pocoservice         I  VM has multidex support, MultiDex support library is disabled.
2024-10-16 16:26:38.714 25325-25325 MonitoringInstr         com.netease.open.pocoservice         I  Instrumentation started!
2024-10-16 16:26:38.992 25325-25325 AndroidJUnitRunner      com.netease.open.pocoservice         I  onCreate Bundle[{class=com.netease.open.pocoservice.InstrumentedTestAsLauncher, debug=false}]
2024-10-16 16:26:38.995 25325-25325 TestEventClient         com.netease.open.pocoservice         V  No service name argument was given (testDiscoveryService, testRunEventService or orchestratorService)
2024-10-16 16:26:38.997 25325-25361 AndroidJUnitRunner      com.netease.open.pocoservice         D  onStart is called.
2024-10-16 16:26:39.001 25325-25325 Quality                 com.netease.open.pocoservice         I  ActivityThread: bindApplication delay 1071 com.netease.open.pocoservice 25325
2024-10-16 16:26:39.003 25325-25355 Quality                 com.netease.open.pocoservice         I  Blocked msg = Package name: com.netease.open.pocoservice [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s99ms what=110 target=android.app.ActivityThread$H obj=AppBindData{appInfo=ApplicationInfo{461a967 com.netease.open.pocoservice}} } took 1071 ms
2024-10-16 16:26:39.026 25325-25364 libMEOW                 com.netease.open.pocoservice         D  meow new tls: 0xb40000778408b8c0
2024-10-16 16:26:39.026 25325-25364 libMEOW                 com.netease.open.pocoservice         D  meow reload base cfg path: na
2024-10-16 16:26:39.026 25325-25364 libMEOW                 com.netease.open.pocoservice         D  meow reload overlay cfg path: na
2024-10-16 16:26:39.030 25325-25364 QT                      com.netease.open.pocoservice         E  [QT]file does not exist
2024-10-16 16:26:39.031 25325-25364 libMEOW                 com.netease.open.pocoservice         D  applied 1 plugins for [com.netease.open.pocoservice]:
2024-10-16 16:26:39.032 25325-25364 libMEOW                 com.netease.open.pocoservice         D    plugin 1: [libMEOW_gift.so]: 0xb400007774a9fd40
2024-10-16 16:26:39.032 25325-25364 libMEOW                 com.netease.open.pocoservice         D  rebuild call chain: 0xb4000077840aa140
2024-10-16 16:26:39.033 25325-25364 libMEOW                 com.netease.open.pocoservice         D  meow delete tls: 0xb40000778408b8c0
2024-10-16 16:26:39.166 25325-25325 MultiApp.Impl           com.netease.open.pocoservice         E  OplusMultiAppImpl
2024-10-16 16:26:39.167 25325-25325 AppCompatDelegate       com.netease.open.pocoservice         D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2024-10-16 16:26:39.199 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: PRE_ON_CREATE
2024-10-16 16:26:39.242 25325-25325 oplus.andr...actoryImpl com.netease.open.pocoservice         I  Unknow feature:IOplusTextViewRTLUtilForUG
2024-10-16 16:26:39.338 25325-25325 pen.pocoservic          com.netease.open.pocoservice         W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2024-10-16 16:26:39.338 25325-25325 pen.pocoservic          com.netease.open.pocoservice         W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2024-10-16 16:26:39.401 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: CREATED
2024-10-16 16:26:39.405 25325-25325 Quality                 com.netease.open.pocoservice         I  ActivityThread: activityStart delay 402 com.netease.open.pocoservice 25325
2024-10-16 16:26:39.408 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: STARTED
2024-10-16 16:26:39.413 25325-25325 PocoService             com.netease.open.pocoservice         I  onResume
2024-10-16 16:26:39.443 25325-25325 Compatibil...geReporter com.netease.open.pocoservice         D  Compat change id reported: 147798919; UID 10266; state: ENABLED
2024-10-16 16:26:39.465 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: RESUMED
2024-10-16 16:26:39.470 25325-25325 OplusInputMethodUtil    com.netease.open.pocoservice         D  init DEBUG to false, update DEBUG_IME to false
2024-10-16 16:26:39.470 25325-25325 OplusInputMethodUtil    com.netease.open.pocoservice         D  init DEBUG to false, update DEBUG_IME to false
2024-10-16 16:26:39.480 25325-25325 SurfaceFactory          com.netease.open.pocoservice         I  [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@263c81a
2024-10-16 16:26:39.484 25325-25325 MsyncFactory            com.netease.open.pocoservice         I  [static] sMsyncFactory = com.mediatek.view.impl.MsyncFactoryImpl@9904f4b
2024-10-16 16:26:39.487 25325-25365 OpenMsyncAppList        com.netease.open.pocoservice         D  loadTunerAppList + 
2024-10-16 16:26:39.499 25325-25365 OpenMsyncAppList        com.netease.open.pocoservice         D  loadTunerAppList - 
2024-10-16 16:26:39.503 25325-25325 OplusSlideAnimOptHelper com.netease.open.pocoservice         I  checkListMode: is blacklist mode = true
2024-10-16 16:26:39.507 25325-25325 OplusSlideAnimOptHelper com.netease.open.pocoservice         D  com.netease.open.pocoservice scrollEffectOpt enable = true
2024-10-16 16:26:39.535 25325-25325 WindowManager           com.netease.open.pocoservice         D  Add to mViews: DecorView@28593d4[TestActivity],pkg= com.netease.open.pocoservice
2024-10-16 16:26:39.550 25325-25362 ExtensionsLoader        com.netease.open.pocoservice         D  createInstance(64bit) : createExtendedFactory
2024-10-16 16:26:39.563 25325-25362 ExtensionsLoader        com.netease.open.pocoservice         D  Opened libhwuiextimpl.so
2024-10-16 16:26:39.563 25325-25325 ExtensionsLoader        com.netease.open.pocoservice         D  createInstance(64bit) : createExtendedFactory
2024-10-16 16:26:39.565 25325-25325 ExtensionsLoader        com.netease.open.pocoservice         D  Opened libSchedAssistExtImpl.so
2024-10-16 16:26:39.565 25325-25325 pen.pocoservic          com.netease.open.pocoservice         E  ofbOpen failed with error=No such file or directory
2024-10-16 16:26:39.565 25325-25325 pen.pocoservic          com.netease.open.pocoservice         E  sysOpen failed with error=No such file or directory
2024-10-16 16:26:39.573 25325-25325 ViewRootIm...tActivity] com.netease.open.pocoservice         D  hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
2024-10-16 16:26:39.590 25325-25325 libMEOW                 com.netease.open.pocoservice         D  meow new tls: 0xb40000771b2803c0
2024-10-16 16:26:39.591 25325-25325 libMEOW                 com.netease.open.pocoservice         D  applied 1 plugins for [com.netease.open.pocoservice]:
2024-10-16 16:26:39.591 25325-25325 libMEOW                 com.netease.open.pocoservice         D    plugin 1: [libMEOW_gift.so]: 0xb400007774a9fd40
2024-10-16 16:26:39.592 25325-25325 libMEOW                 com.netease.open.pocoservice         D  rebuild call chain: 0xb40000771b28f740
2024-10-16 16:26:39.610 25325-25325 nativeloader            com.netease.open.pocoservice         D  Load libpowerhalwrap_jni.so using system ns (caller=/system/framework/mediatek-framework.jar): ok
2024-10-16 16:26:39.614 25325-25325 PowerHalWrapper         com.netease.open.pocoservice         I  PowerHalWrapper.getInstance 
2024-10-16 16:26:39.621 25325-25325 MonitoringInstr         com.netease.open.pocoservice         I  No JSBridge.
2024-10-16 16:26:39.629 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: PAUSED
2024-10-16 16:26:39.640 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: STOPPED
2024-10-16 16:26:39.764 25325-25361 TestRequestBuilder      com.netease.open.pocoservice         D  Skipping class path scanning and directly running [com.netease.open.pocoservice.InstrumentedTestAsLauncher]
2024-10-16 16:26:39.803 25325-25361 AndroidJUnitRunner      com.netease.open.pocoservice         D  Use the raw file system for managing file I/O.
2024-10-16 16:26:39.810 25325-25361 TestExecutor            com.netease.open.pocoservice         D  Adding listener androidx.test.internal.runner.listener.LogRunListener
2024-10-16 16:26:39.811 25325-25361 TestExecutor            com.netease.open.pocoservice         D  Adding listener androidx.test.internal.runner.listener.InstrumentationResultPrinter
2024-10-16 16:26:39.811 25325-25361 TestExecutor            com.netease.open.pocoservice         D  Adding listener androidx.test.internal.runner.listener.ActivityFinisherRunListener
2024-10-16 16:26:39.811 25325-25361 TestExecutor            com.netease.open.pocoservice         D  Adding listener androidx.test.internal.runner.listener.TraceRunListener
2024-10-16 16:26:39.821 25325-25361 TestRunner              com.netease.open.pocoservice         I  run started: 1 tests
2024-10-16 16:26:39.826 25325-25361 TestRunner              com.netease.open.pocoservice         I  started: launch(com.netease.open.pocoservice.InstrumentedTestAsLauncher)
2024-10-16 16:26:39.830 25325-25325 MonitoringInstr         com.netease.open.pocoservice         I  Finishing activity: com.netease.open.pocoservice.TestActivity@7a6817b
2024-10-16 16:26:39.839 25325-25325 LifecycleMonitor        com.netease.open.pocoservice         D  Lifecycle status change: com.netease.open.pocoservice.TestActivity@7a6817b in: DESTROYED
2024-10-16 16:26:39.841 25325-25325 OplusScrollToTopManager com.netease.open.pocoservice         D  unregisterGuidePopupDismissReceiverInSystemUI
2024-10-16 16:26:39.842 25325-25325 OplusScrollToTopManager com.netease.open.pocoservice         D  Receiver not registered: android.view.OplusScrollToTopManager$1@6ac78a3
2024-10-16 16:26:39.843 25325-25325 OplusScrollToTopManager com.netease.open.pocoservice         D  unregisterSystemUIBroadcastReceiver 
2024-10-16 16:26:39.844 25325-25325 OplusScrollToTopManager com.netease.open.pocoservice         D  java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@54337a0
2024-10-16 16:26:39.847 25325-25325 ZoomWindowDecorView     com.netease.open.pocoservice         V  removeZoomView
2024-10-16 16:26:39.849 25325-25325 View                    com.netease.open.pocoservice         D  [Warning] assignParent to null: this = DecorView@28593d4[TestActivity]
2024-10-16 16:26:39.858 25325-25361 TestRunner              com.netease.open.pocoservice         E  failed: launch(com.netease.open.pocoservice.InstrumentedTestAsLauncher)
2024-10-16 16:26:39.858 25325-25361 TestRunner              com.netease.open.pocoservice         E  ----- begin exception -----
2024-10-16 16:26:39.873 25325-25361 TestRunner              com.netease.open.pocoservice         E  java.lang.RuntimeException: Error while connecting UiAutomation@e519f59[id=-1, flags=0]
                                                                                                    	at android.app.UiAutomation.connectWithTimeout(UiAutomation.java:333)
                                                                                                    	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2236)
                                                                                                    	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2181)
                                                                                                    	at com.netease.open.pocoservice.UiAutomationConnection.get(UiAutomationConnection.java:19)
                                                                                                    	at com.netease.open.pocoservice.ServerForHierarchyViewer.<init>(ServerForHierarchyViewer.java:48)
                                                                                                    	at com.netease.open.pocoservice.InstrumentedTestAsLauncher.launch(InstrumentedTestAsLauncher.java:33)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
                                                                                                    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                                                    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
                                                                                                    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
                                                                                                    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2269)
                                                                                                    Caused by: android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:641)
                                                                                                    	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:507)
                                                                                                    	at android.app.UiAutomation.connectWithTimeout(UiAutomation.java:324)
                                                                                                    	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2236) 
                                                                                                    	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2181) 
                                                                                                    	at com.netease.open.pocoservice.UiAutomationConnection.get(UiAutomationConnection.java:19) 
                                                                                                    	at com.netease.open.pocoservice.ServerForHierarchyViewer.<init>(ServerForHierarchyViewer.java:48) 
                                                                                                    	at com.netease.open.pocoservice.InstrumentedTestAsLauncher.launch(InstrumentedTestAsLauncher.java:33) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) 
                                                                                                    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
                                                                                                    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) 
                                                                                                    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) 
                                                                                                    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) 
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) 
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) 
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
                                                                                                    	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162) 
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128) 
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27) 
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67) 
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58) 
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446) 
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2269) 
2024-10-16 16:26:39.873 25325-25361 TestRunner              com.netease.open.pocoservice         E  ----- end exception -----
2024-10-16 16:26:39.902 25325-25361 TestRunner              com.netease.open.pocoservice         I  finished: launch(com.netease.open.pocoservice.InstrumentedTestAsLauncher)
2024-10-16 16:26:39.911 25325-25361 TestRunner              com.netease.open.pocoservice         I  run finished: 1 tests, 1 failed, 0 ignored
**2024-10-16 16:26:39.949 25325-25361 AndroidRuntime          com.netease.open.pocoservice         E  FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner**
                                                                                                    Process: com.netease.open.pocoservice, PID: 25325
                                                                                                    java.lang.IllegalStateException: Cannot call disconnect() while connecting UiAutomation@e519f59[id=-1, flags=0]
                                                                                                    	at android.app.UiAutomation.disconnect(UiAutomation.java:377)
                                                                                                    	at android.app.Instrumentation.finish(Instrumentation.java:281)
                                                                                                    	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:422)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:457)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2269)
**2024-10-16 16:26:39.956 25325-25361 Process                 com.netease.open.pocoservice         I  Sending signal. PID: 25325 SIG: 9**
2024-10-16 16:26:41.444 25456-25456 OplusFeatureCache       com.netease.open.pocoservice         I  Milliseconds spent on init(): 131
2024-10-16 16:26:41.459 25456-25456 LoadedApk               com.netease.open.pocoservice         D  mApplicationInfo overrideDisplayId:null
2024-10-16 16:26:41.464 25456-25456 ziparchive              com.netease.open.pocoservice         W  Unable to open '/data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/base.dm': No such file or directory
2024-10-16 16:26:41.464 25456-25456 ziparchive              com.netease.open.pocoservice         W  Unable to open '/data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/base.dm': No such file or directory
2024-10-16 16:26:41.914 25456-25456 nativeloader            com.netease.open.pocoservice         D  Configuring clns-4 for other apk /data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.netease.open.pocoservice
2024-10-16 16:26:41.917 25456-25456 Quality                 com.netease.open.pocoservice         I  ActivityThread: createClassLoader delay 455 /data/app/~~DOlSPEhnJ_I0E_7IXT9HOg==/com.netease.open.pocoservice-qjjDNZcqo4Ux5q0I-2ql3g==/base.apk 25456
2024-10-16 16:26:41.923 25456-25456 Quality                 com.netease.open.pocoservice         I  ActivityThread: createOrUpdateClassLoaderLocked delay 463 com.netease.open.pocoservice 25456
2024-10-16 16:26:41.950 25456-25456 GraphicsEnvironment     com.netease.open.pocoservice         V  ANGLE Developer option for 'com.netease.open.pocoservice' set to: 'default'
2024-10-16 16:26:41.951 25456-25456 GraphicsEnvironment     com.netease.open.pocoservice         V  Neither updatable production driver nor prerelease driver is supported.
2024-10-16 16:26:41.981 25456-25456 NetworkSecurityConfig   com.netease.open.pocoservice         D  No Network Security Config specified, using platform default
2024-10-16 16:26:41.984 25456-25456 NetworkSecurityConfig   com.netease.open.pocoservice         D  No Network Security Config specified, using platform default


```

**复现步骤**
使用 Airtest IDE 1.2.17 在连接真机，点击 Poco 辅助窗UI渲染数之后，手机上不断提示 poco service is running
1. 使用 Airtest IDE 1.2.17 连接真机
2. 点击 Poco 辅助窗UI渲染数之后
3. 之后就发现手机上不断提示 poco service is running

**预期效果**
PocoService 正常运行

**相关截图**
![image](https://github.com/user-attachments/assets/8ec178a6-e82c-422a-8d72-7e99ab35cd4f)

**python 版本:** `Python 3.10.14`

**poco 版本:** `1.0.69`
**PoCoService App Version: `1.0.0.68`

**设备:**
 - 型号: OPPO A78
 - 系统: Android 12

**其他相关环境信息**
cacOS sonoma 14.5 上运行Airtest IDE

**Comment by ppnijia** [comment]
同问 怎么解决？？？
