### ISSUE TITLE
AttributeError: 'FrozenPoco' object has no attribute 'screenshot_each_action'

### ISSUE THREAD

**Issue by zeryter** [AirtestProject/Poco#64]
```python
/Users/xxx/venv/lib/python3.6/site-packages/poco/pocofw.py:474: UserWarning: Error occurred at pre action stage.
Traceback (most recent call last):
  File "/Users/xxx/venv/lib/python3.6/site-packages/poco/pocofw.py", line 472, in pre_action
    cb(self, action, ui, args)
  File "/Users/xxx/venv/lib/python3.6/site-packages/poco/drivers/android/uiautomation.py", line 281, in on_pre_action
    if self.screenshot_each_action:
AttributeError: 'FrozenPoco' object has no attribute 'screenshot_each_action'

  warnings.warn("Error occurred at pre action stage.\n{}".format(traceback.format_exc()))
```

**Comment by zeryter** [comment]
ok  thanks
