### ISSUE TITLE
使用my-testflow工程经常运行不起来

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#65]
cap -i
[02:57:56][DEBUG]<airtest.core.android.adb> D:/eclipse/sdk/platform-tools/adb.ex
e -s K50GLD2681200191 shell monkey -p com.mt.mtxx.mtxx -c android.intent.categor
y.LAUNCHER 1
Traceback (most recent call last):
  File "C:\Users\Administrator\my-testflow\testflow\scripts\mtxx.py", line 29, i
n <module>
    pocounit.main()
  File "D:\Program Files\Python3\lib\site-packages\pocounit\__init__.py", line 4
5, in main
    result = runner.run(suite)
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsL
auncher:'
  File "D:\Program Files\Python3\lib\unittest\runner.py", line 176, in run
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
    test(result)
  File "D:\Program Files\Python3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\Program Files\Python3\lib\site-packages\pocounit\suite.py", line 15,
in run
    super(PocoTestSuite, self).run(result, debug)
  File "D:\Program Files\Python3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\Program Files\Python3\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "D:\Program Files\Python3\lib\site-packages\pocounit\case.py", line 201,
in run
    ret = self._super_run_modified(result)
  File "D:\Program Files\Python3\lib\site-packages\pocounit\case.py", line 267,
in _super_run_modified
    self.on_errors(outcome.errors)
  File "D:\Program Files\Python3\lib\site-packages\pocounit\case.py", line 351,
in on_errors
    site_snapshot.snapshot('testcase_err_{}'.format(errors[0][1]))
  File "D:\Program Files\Python3\lib\site-packages\pocounit\result\site_snapshot
.py", line 38, in snapshot
    self.snapshot_screen(site_id)
  File "D:\Program Files\Python3\lib\site-packages\pocounit\result\site_snapshot
.py", line 60, in snapshot_screen
    b64img, fmt = self.poco.snapshot()
  File "D:\Program Files\Python3\lib\site-packages\poco\pocofw.py", line 419, in
 snapshot
    return self.agent.screen.getScreen(width)
  File "D:\Program Files\Python3\lib\site-packages\poco\drivers\android\uiautoma
tion.py", line 73, in getScreen
    b64img = self.screen.getScreen(width)
  File "D:\Program Files\Python3\lib\site-packages\hrpc\object_proxy.py", line 9
2, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *
args))
  File "D:\Program Files\Python3\lib\site-packages\hrpc\client.py", line 63, in
evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_pro
xy._invocation_path__})
  File "D:\Program Files\Python3\lib\site-packages\hrpc\transport\http.py", line
 23, in send
    r = requests.post(self.endpoint, data=json.dumps(req), headers={'Content-Typ
e': 'application/json'})
  File "D:\Program Files\Python3\lib\site-packages\requests\api.py", line 112, i
n post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Program Files\Python3\lib\site-packages\requests\api.py", line 58, in
 request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Program Files\Python3\lib\site-packages\requests\sessions.py", line 5
03, in request
    prep.url, proxies, stream, verify, cert
  File "D:\Program Files\Python3\lib\site-packages\requests\sessions.py", line 6
76, in merge_environment_settings
    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "D:\Program Files\Python3\lib\site-packages\requests\utils.py", line 760,
 in get_environ_proxies
    if should_bypass_proxies(url, no_proxy=no_proxy):
  File "D:\Program Files\Python3\lib\site-packages\requests\utils.py", line 744,
 in should_bypass_proxies
    bypass = proxy_bypass(parsed.hostname)
  File "D:\Program Files\Python3\lib\site-packages\requests\utils.py", line 90,
in proxy_bypass
    if getproxies_environment():
  File "D:\Program Files\Python3\lib\urllib\request.py", line 2480, in getproxie
s_environment
    for name, value in os.environ.items():
  File "D:\Program Files\Python3\lib\_collections_abc.py", line 743, in __iter__

    for key in self._mapping:
  File "D:\Program Files\Python3\lib\os.py", line 691, in __iter__
    yield self.decodekey(key)
  File "D:\Program Files\Python3\lib\site-packages\pocounit\result\trace.py", li
ne 48, in tracer
    def tracer(frame, event, arg):
KeyboardInterrupt
[02:58:17][DEBUG]<airtest.core.android.adb> D:/eclipse/sdk/platform-tools/adb.ex
e -s K50GLD2681200191 forward --remove tcp:17290
[02:58:17][DEBUG]<airtest.core.android.adb> D:/eclipse/sdk/platform-tools/adb.ex
e -s K50GLD2681200191 forward --remove tcp:16779

**Comment by adolli** [comment]
这个感觉还是手机上对PocoService不兼容的原因，有换过其他手机测试吗？
