### ISSUE TITLE
手动卸载pocoservice后在手机上运行airtest时提示安装pocoservice失败

### ISSUE THREAD

**Issue by guoxinbuct** [AirtestProject/Poco#68]
[Start running..]
save log in 
```
'C:\Users\lenovo\AppData\Local\Temp\AirtestIDE\scripts\038d01f2ead18d2827148b0604d4e8f2'
b'D:\\software\\AirtestIDE_2018-07-20_py3_win64\\test001.air\\test001.py:68: SyntaxWarning: assertion is always true, perhaps remove parentheses?\r\n  assert(poco(\'com.test.debug:id/live_course_item_date\').exists(),"\xce\xb4\xc4\xdc\xb3\xc9\xb9\xa6\xbd\xf8\xc8\xeb\xb5\xbd\xbf\xce\xb3\xcc\xb4\xf3\xb8\xd9\xd2\xb3\xc3\xe6\xa3\xa1")\r\n\r\n'installed version is None, installer version is 39. force_reinstall=False
[  2%] /data/local/tmp/pocoservice-debug.apk
[  4%] /data/local/tmp/pocoservice-debug.apk
[  7%] /data/local/tmp/pocoservice-debug.apk
[  9%] /data/local/tmp/pocoservice-debug.apk
[ 12%] /data/local/tmp/pocoservice-debug.apk
[ 14%] /data/local/tmp/pocoservice-debug.apk
[ 17%] /data/local/tmp/pocoservice-debug.apk
[ 19%] /data/local/tmp/pocoservice-debug.apk
[ 22%] /data/local/tmp/pocoservice-debug.apk
[ 24%] /data/local/tmp/pocoservice-debug.apk
[ 27%] /data/local/tmp/pocoservice-debug.apk
[ 29%] /data/local/tmp/pocoservice-debug.apk
[ 31%] /data/local/tmp/pocoservice-debug.apk
[ 34%] /data/local/tmp/pocoservice-debug.apk
[ 36%] /data/local/tmp/pocoservice-debug.apk
[ 39%] /data/local/tmp/pocoservice-debug.apk
[ 41%] /data/local/tmp/pocoservice-debug.apk
[ 44%] /data/local/tmp/pocoservice-debug.apk
[ 46%] /data/local/tmp/pocoservice-debug.apk
[ 49%] /data/local/tmp/pocoservice-debug.apk
[ 51%] /data/local/tmp/pocoservice-debug.apk
[ 54%] /data/local/tmp/pocoservice-debug.apk
[ 56%] /data/local/tmp/pocoservice-debug.apk
[ 58%] /data/local/tmp/pocoservice-debug.apk
[ 61%] /data/local/tmp/pocoservice-debug.apk
[ 63%] /data/local/tmp/pocoservice-debug.apk
[ 66%] /data/local/tmp/pocoservice-debug.apk
[ 68%] /data/local/tmp/pocoservice-debug.apk
[ 71%] /data/local/tmp/pocoservice-debug.apk
[ 73%] /data/local/tmp/pocoservice-debug.apk
[ 76%] /data/local/tmp/pocoservice-debug.apk
[ 78%] /data/local/tmp/pocoservice-debug.apk
[ 81%] /data/local/tmp/pocoservice-debug.apk
[ 83%] /data/local/tmp/pocoservice-debug.apk
[ 86%] /data/local/tmp/pocoservice-debug.apk
[ 88%] /data/local/tmp/pocoservice-debug.apk
[ 90%] /data/local/tmp/pocoservice-debug.apk
[ 93%] /data/local/tmp/pocoservice-debug.apk
[ 95%] /data/local/tmp/pocoservice-debug.apk
[ 98%] /data/local/tmp/pocoservice-debug.apk
[100%] /data/local/tmp/pocoservice-debug.apk
D:\software\AirtestIDE_2018-08-07_py3_win64(1)\AirtestIDE_2018-08-07_py3_win64\poco\drivers\android\lib\pocoservice-debug.apk: 1 file pushed. 6.1 MB/s (2665980 bytes in 0.414s)
	pkg: /data/local/tmp/pocoservice-debug.apk

Failure [INSTALL_FAILED_ALREADY_EXISTS]
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "D:\software\AirtestIDE_2018-07-20_py3_win64\test001.air\test001.py", line 7, in <module>
    poco = AndroidUiautomationPoco(force_restart=True)
  File "poco\drivers\android\uiautomation.py", line 150, in __init__
  File "poco\drivers\android\uiautomation.py", line 189, in _install_service
  File "poco\drivers\android\utils\installation.py", line 31, in install
  File "airtest\core\android\adb.py", line 564, in install_app
airtest.core.error.AirtestError: 'Installation Failure'

----------------------------------------------------------------------
Ran 1 test in 15.066s

FAILED (errors=1)
[Finished]

============================================================
```

**Comment by adolli** [comment]
尝试下手动安装pocoservice-debug.apk，还不行的话，先卸载掉原有的再试试。另一种可能是无法获取手机上已安装的pocoservice的版本，导致重复安装报错。

**Comment by guoxinbuct** [comment]
手动安装是可以的，就是运行脚本的时候自动安装不行

**Comment by adolli** [comment]
看样子是这台手机上无法获取已安装app的版本号了，目前没有什么好办法解决。

**Comment by guoxinbuct** [comment]
好的  谢谢





在 2018-08-16 10:29:21，"adolli" <notifications@github.com> 写道：


看样子是这台手机上无法获取已安装app的版本号了，目前没有什么好办法解决。

**Comment by PetterZhukov** [comment]
不懂就问，pocoservice-debug.apk在哪里下呀，有人知道吗，在线等qvq
