### ISSUE TITLE
ImportError: cannot import name Poco

### ISSUE THREAD

**Issue by youbaowu** [AirtestProject/Poco#7]
Traceback (most recent call last):
  File "D:\pycharm-professional-2017.2.3\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\pycharm-professional-2017.2.3\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/UIAutomator.py", line 13, in <module>
    from poco.drivers.android.uiautomation import AndroidUiautomationPoco
  File "D:\Django\python\lib\site-packages\poco\drivers\android\uiautomation.py", line 23, in <module>
    from poco import Poco
ImportError: cannot import name Poco

**Comment by adolli** [comment]
It seems that you install an incorrect poco package. Try the following command to fix it.

``` bash
pip uninstall poco
pip install -U pocoui
```

**Comment by adolli** [comment]
If this error still appears. Please try
```bash
pip uninstall pocoui
pip install pocoui
```

or reopen this issue and let me know more error information.
