### ISSUE TITLE
poco辅助窗口选定andro时，日志报错

### ISSUE THREAD

**Issue by lewis828** [AirtestProject/Poco#73]
问题描述：
poco辅助窗口选定andro时，日志报错

报错信息：
```
initializing Android poco.
[10:39:42][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell dumpsys activity top
[10:39:42][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell dumpsys package com.netease.nie.yosemite
[10:39:42][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[10:39:42][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell settings get secure default_input_method
[10:39:42][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell ime list -a
[10:39:43][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell dumpsys package com.netease.open.pocoservice
installed version is 39, installer version is 39. force_reinstall=False
[10:39:43][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[10:39:43][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 forward --no-rebind tcp:12512 tcp:10080
[10:39:43][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 forward --no-rebind tcp:17982 tcp:10081
[10:39:43][DEBUG]<airtest.core.android.adb> C:\Users\lewis\Desktop\AirtestIDE_2018-08-07_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.5.9.3:7457 shell ps
[pocoservice.apk] background daemon started.
Exception in thread Thread-724:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "poco\drivers\android\uiautomation.py", line 206, in loop
AttributeError: 'NoneType' object has no attribute 'communicate'

```

**复现步骤**
1. 接入并打开app
2. poco辅助窗选择android
3. 查看airtest日志
4. 日志报错，详情见上方贴的
5.driver screen也无法选择和定位元素

**预期效果**
1.没报错
2.能获取到相关的定位元素

**相关截图**

**python 版本:** `python3.4`
**poco 版本:** `1.0.69`
**设备:**
 - 型号: 华为P9 ，mate9
 - 系统: Android 7.0
 - app: 是一个内嵌H5的app
-环境系统：windows 10
-airtest:最新版本
**其他相关环境信息**
第一次运行的时候是可以获取到元素的
但是运行一次后，就无法定位元素

**Comment by lewis828** [comment]
android 我打错了……

**Comment by adolli** [comment]
最新版本的AirtestIDE中已修复此问题，请更新到最新版。谢谢！
