### ISSUE TITLE
poco选择的安卓，然后录制脚本，回放时报错

### ISSUE THREAD

**Issue by bboxu** [AirtestProject/Poco#77]
```py
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

poco("com.tencent.android.qqdownloader:id/f4").child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("android.widget.RelativeLayout")[1].child("android.widget.ImageView")[0].click()
poco("com.tencent.android.qqdownloader:id/f4").child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("android.widget.RelativeLayout")[2].child("android.widget.ImageView")[0].click()
poco("com.tencent.android.qqdownloader:id/f4").child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("android.widget.RelativeLayout")[3].child("android.widget.ImageView")[1].click()
poco("com.tencent.android.qqdownloader:id/f4").child("android.widget.RelativeLayout").child("android.widget.LinearLayout").child("android.widget.RelativeLayout")[4].child("android.widget.ImageView")[1].click()
```

日志：
[Start running..]
```
save log in 'C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\921f977891d835ca80f44b3ad7585fee'
installed version is 39, installer version is 39. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
[pocoservice.apk] background daemon started.
Exception in thread Thread-22:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "poco\drivers\android\uiautomation.py", line 206, in loop
AttributeError: 'NoneType' object has no attribute 'communicate'

----------------------------------------------------------------------
Ran 1 test in 24.356s

OK
[Finished]
```

**Comment by adolli** [comment]
请更新AirtestIDE，此bug已修复。谢谢。
