### ISSUE TITLE
Cocos2dx-lua集成后未能在AirtestIDE上显示控件树

### ISSUE THREAD

**Issue by Danieltdd** [AirtestProject/Poco#81]
**描述问题bug**

集成poco之后，在AirtestIDE上不现实控件树

**复现步骤**

1、集成poco到App
2、打开App（显示服务启动成功：[LUA-print] [poco] server listens on tcp://*:15004）
3、AirtestIDE选择cocos-lua刷新控件树：[LUA-print] [poco] new client accepted	127.0.0.1	nil

**预期效果**
AirtestIDE显示控件树

**相关截图**
1、通过添加日志：发现能够正确的接手到dump请求：
[LUA-print] [poco] onRequest	table: 0xc90cd120	Dump	table: 0xc90cd3e0
2、在client返回前打印返回信息，结构如下
```
￼I/MockLuaCallProxy: [LUA-print] [poco] client send	{
      id = "52158b5b-7240-486b-a484-67f83ddc39fb",
      jsonrpc = "2.0",
      result = {
        children = { {
            children = { {
                children = { {
                    name = "Image_bg1",
                    payload = {
                      anchorPoint = { 0.5, 0.5 },
                      desc = "ImageView",
                      enabled = true,
                      name = "Image_bg1",
                      pos = { 0.5, 0.5 },
                      rotation = 0,
                      scale = { 1.2000000476837, 1 },
                      size = { 0.27351189540805, 1.2173913043478 },
                      skew = { 0, 0 },
                      tag = 6,
                      touchable = false,
                      type = "ImageView",
                      visible = true,
                      zOrders = {
                        global = 0,
                        local = 0
                      }
                    }
                  }, {
                    name = "Image_bg2",
                    payload = {
                      anchorPoint = { 0.5, 0.5 },
                      desc = "ImageView",
                      enabled = true,
                      name = "Image_bg2",
                      pos = { 0.52661269851982, 0.50220001083443 },
                      rotation = 0,
                      scale = { 1, 1 },
                      size = { 0.20422221523801, 0.68215892053973 },
                      skew = { 0, 0 },
                      tag = 7,
                      touchable = false,
                      type = "ImageView",
                      visible = true,
                      zOrders = {
                        global = 0,
                        local = 0
                      }
                    }
                  }, {
                    children = { {
                        children = { {
                            children = { {
                                children = { {
                                    name = "<Node | Tag = -1",
                                    payload = {
                                      anchorPoint = { 0.5, 0.5 },
                                      desc = "<Node | Tag = -1",
                                      name = "<Node | Tag = -1",
                                      pos = { 0.39606547974494, 0.71983875005856 },
                                      rotation = 0,
                                      scale = { 1, 1 },
                                      size = { 0.041573808102024, 0.086206896551724 },
                                      skew = { 0, 0 },
                                      tag = -1,
                                      type = "ProgressTimer",
                                      visible = true,
                                      zOrders = {
                                        global = 0,
                                        local = 0
                                      }
                                    }
                                  } },
                                name = "progressBar",
                                payload = {
                                  anchorPoint = { 0.5, 0.5 },
                                  desc = "<Sprite | Tag = 37, TextureID = 1>",
                                  name = "progressBar",
                                  pos = { 0.39606547974494, 0.71946393746486 },
                                  rotation = 0,
                                  scale = { 1, 1 },
                                  size = { 0.041573808102024, 0.086206896551724 },
                                  skew = { 0, 0 },
                                  tag = 37,
                                  type = "Sprite",
                                  visible = true,
                                  zOrders = {
                                    global = 0,
                                    local = 0
                                  }
                                }
                              }, {
                                name = "fold01",
                                payload = {
                                  anchorPoint = { 0.5, 0.5 },
                                  desc = "<Sprite | Tag = 39, TextureID = 1>",
                                  name = "fold01",
                                  pos = { 0.39606547974494, 0.71946393746486 
￼￼```

**设备:**
 - 型号: 三星S8
 - 系统:Android 8.1


**其他相关环境信息**
mac环境下AirtestIDE使用1.0.0RC版本

**Comment by Danieltdd** [comment]
错误信息如下：
poco_data: /Applications/AirtestIDE.app/Contents/MacOS/refresh_error_data.json
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/poco_window.py", line 338, in refreshData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 516, in loadData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 93, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 219, in setupModelData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 199, in setupModelData
KeyError: 'name'
Refresh error!

**Comment by Danieltdd** [comment]
另外使用独立的PocoHierarchyView1.0.5版本能够正常显示控件树

**Comment by rockywhisper** [comment]
@Danieltdd  你好，我们马上查证问题，会尽快放出修复版本。

**Comment by yimelia** [comment]
@Danieltdd hi, 可以试一下目前官网最新版本看看还是否存在这个问题，如果问题仍然存在，请reopen这个issue，我们再继续查证。

**Comment by Danieltdd** [comment]
KeyError: 'type'
Refresh error!
poco_data: /Applications/AirtestIDE.app/Contents/MacOS/refresh_error_data.json
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/poco_window.py", line 338, in refreshData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 516, in loadData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 93, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 219, in setupModelData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 201, in setupModelData
KeyError: 'type'
Refresh error!
poco_data: /Applications/AirtestIDE.app/Contents/MacOS/refresh_error_data.json
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/poco_window.py", line 338, in refreshData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 516, in loadData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 93, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 219, in setupModelData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 201, in setupModelData
KeyError: 'type'
Refresh error!
poco_data: /Applications/AirtestIDE.app/Contents/MacOS/refresh_error_data.json
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/poco_window.py", line 338, in refreshData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 516, in loadData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 93, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 219, in setupModelData
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/poco/gui/tree.py", line 201, in setupModelData
KeyError: 'type'
Refresh error!

**Comment by Danieltdd** [comment]
还是有错！不过这次Key不同了

**Comment by Danieltdd** [comment]
> @Danieltdd hi, 可以试一下目前官网最新版本看看还是否存在这个问题，如果问题仍然存在，请reopen这个issue，我们再继续查证。

还是有错，请看日志

**Comment by zzldjkzxf** [comment]
@Danieltdd  这个报错是节点缺少了"type“属性， 我们再次加了容错，会在今天放出来版本修复。如有问题可再次反馈

**Comment by liuss01** [comment]
我们继承lua SDK后，有个报错，报错信息如下，报错代码跟上面的一样，但是行号不一样。这个代码源码哪里有呢？
[11:10:10][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[11:10:10][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[11:10:10][DEBUG]<airtest.core.android.minicap> (1, 24, 3851, 2220, 1080, 800, 389, 0, 2)
Traceback (most recent call last):
File "app\plugins\poco\poco_window.py", line 352, in refreshData
File "app\plugins\poco\gui\tree.py", line 519, in loadData
File "app\plugins\poco\gui\tree.py", line 477, in checkDiffData
File "app\plugins\poco\gui\tree.py", line 471, in calHashWithTree
File "app\plugins\poco\gui\tree.py", line 471, in calHashWithTree
File "app\plugins\poco\gui\tree.py", line 471, in calHashWithTree
[Previous line repeated 9 more times]
File "app\plugins\poco\gui\tree.py", line 468, in calHashWithTree
File "app\plugins\poco\gui\tree.py", line 461, in calHashWithPos
TypeError: type NoneType doesn't define __round__ method
Refresh error!
poco_data: D:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\refresh_error_data.json

**Comment by liuss01** [comment]
原生的lua SDK

**Comment by ghosthaha** [comment]
> 我们继承lua SDK后，有个报错，报错信息如下，报错代码跟上面的一样，但是行号不一样。这个代码源码哪里有呢？
> [11:10:10][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
> [11:10:10][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
> [11:10:10][DEBUG]<airtest.core.android.minicap> (1, 24, 3851, 2220, 1080, 800, 389, 0, 2)
> Traceback (most recent call last):
> File "app\plugins\poco\poco_window.py", line 352, in refreshData
> File "app\plugins\poco\gui\tree.py", line 519, in loadData
> File "app\plugins\poco\gui\tree.py", line 477, in checkDiffData
> File "app\plugins\poco\gui\tree.py", line 471, in calHashWithTree
> File "app\plugins\poco\gui\tree.py", line 471, in calHashWithTree
> File "app\plugins\poco\gui\tree.py", line 471, in calHashWithTree
> [Previous line repeated 9 more times]
> File "app\plugins\poco\gui\tree.py", line 468, in calHashWithTree
> File "app\plugins\poco\gui\tree.py", line 461, in calHashWithPos
> TypeError: type NoneType doesn't define **round** method
> Refresh error!
> poco_data: D:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\refresh_error_data.json

请问你这个问题解决了吗？我也遇到了同样的问题
