### ISSUE TITLE
pip(10.0.0) install pocoui error

### ISSUE THREAD

**Issue by codeskyblue** [AirtestProject/Poco#9]
This is console log

```
$ pip install -U pocoui
Collecting pocoui
  Using cached pocoui-1.0.35.tar.gz
Requirement not upgraded as not directly required: six in c:\users\hzsunshx\appdata\roaming\python\python36\site-package
s (from pocoui) (1.11.0)
Requirement not upgraded as not directly required: requests in c:\python36\lib\site-packages (from pocoui) (2.18.4)
Requirement not upgraded as not directly required: airtest in c:\python36\lib\site-packages (from pocoui) (1.0.5)
Collecting hrpc (from pocoui)
  Using cached hrpc-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hzsunshx\AppData\Local\Temp\pip-install-av0desud\hrpc\setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\hzsunshx\AppData\Local\Temp\pip-install-av0desud
\hrpc\
```

This can be hot fixed by downgrade pip version to 9.0.1

```
python -m pip install -U pip==9.0.1
```

**Comment by Meteorix** [comment]
@adolli is releasing the fix

**Comment by adolli** [comment]
Fix. Caused by `hrpc`, not poco itself. Please try `pip install -U pocoui` again.
