### ISSUE TITLE
输入文本之后无法进行下一步

### ISSUE THREAD

**Issue by jomicuicui** [AirtestProject/Poco#94]
正确执行test（）之后，就报错了，没办法进行下一步操作：
部分代码：
```py
poco("注册/登录").click()
sleep(1.0)
poco("wxb8cd6b37ae082b32:pages/login/main.html:VISIBLE").child("android.view.View").child("android.view.View").child("android.view.View")[1].child("android.view.View").click()
text("13212312312")
poco("wxb8cd6b37ae082b32:pages/login/main.html:VISIBLE").child("android.view.View").child("android.view.View").child("android.view.View")[2].click()
```
出错节点：执行完text("13212312312")就出错了，不再进行下一步

报错信息：
```
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\g\Desktop\untitled.air\untitled.py", line 26, in <module>
    text("13212312312")
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 366, in text
  File "airtest\core\android\android.py", line 314, in text
  File "airtest\core\android\adb.py", line 364, in shell
airtest.core.error.AdbShellError: stdout[] stderr[Killed 
]
```

**Comment by rockywhisper** [comment]
@jomicuicui  
有没有尝试使用`poco(xxx).set_text()`方法呢？
另外，可以提供下设备信息吗？

**Comment by adolli** [comment]
@jomicuicui 最后报错`Killed`多数是因为`adb shell input`命令或者`adb shell am broadcast`被系统限制了，请在设备相关安全设置里打开一下权限。

**Comment by jomicuicui** [comment]
> @jomicuicui求最后报错`Killed`多数的英文因为`adb shell input`命令或者`adb shell am broadcast`被系统-限制了，请在设备相关安全设置里打开一下权限。
不知道怎么开权限~~~呜呜呜呜
